// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/components/manager-dashboard/manager-dashboard.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnDestroy, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';

import { DocumentationIdentityService } from '../../../core/services/documentation-identity.service';
import type { DocumentationRole } from '../../interfaces/documentation-role';
import { switchMapOnDocumentationContext } from '../../lib/documentation-context-refresh';
import type { DocumentationDocument, DocumentationRequest } from '../../interfaces/documentation-entities';
import { filterByEmployeeScope } from '../../lib/documentation-filters';
import { mapDocumentRequestDto, mapRequestToGeneratedDocument } from '../../lib/documentation-dto-mappers';
import type { HierarchyDrillSelection } from '../../lib/documentation-org-hierarchy';
import { DocumentationApiService } from '../../services/documentation-api.service';
import { DocumentationHierarchyDrillService } from '../../services/documentation-hierarchy-drill.service';
import { DocumentationNavigationService } from '../../services/documentation-navigation.service';
import { DocDrillBarComponent } from '../doc-drill-bar/doc-drill-bar.component';
import { DocIconComponent } from '../doc-icon/doc-icon.component';
import { StatusBadgeComponent } from '../status-badge/status-badge.component';

@Component({
  selector: 'app-manager-dashboard',
  standalone: true,
  imports: [CommonModule, DocIconComponent, StatusBadgeComponent, DocDrillBarComponent],
  templateUrl: './manager-dashboard.component.html',
})
export class ManagerDashboardComponent implements OnInit, OnDestroy {
  @Input({ required: true }) role!: DocumentationRole;

  drill: HierarchyDrillSelection = {};
  private sub = new Subscription();

  loading = true;
  error: string | null = null;
  private allRequests: DocumentationRequest[] = [];

  constructor(
    private readonly hierarchy: DocumentationHierarchyDrillService,
    private readonly nav: DocumentationNavigationService,
    private readonly api: DocumentationApiService,
    private readonly identity: DocumentationIdentityService,
  ) {}

  ngOnInit(): void {
    this.sub.add(this.hierarchy.drill$.subscribe((d) => (this.drill = d)));
    this.sub.add(
      switchMapOnDocumentationContext(this.identity, () => this.api.getAllDocumentRequests()).subscribe({
        next: (rows) => {
          this.allRequests = rows.map(mapDocumentRequestDto);
          this.loading = false;
          this.error = null;
        },
        error: () => {
          this.allRequests = [];
          this.loading = false;
          this.error = 'Impossible de charger les demandes.';
        },
      }),
    );
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }

  get teamRequests(): DocumentationRequest[] {
    return filterByEmployeeScope(
      this.allRequests,
      this.role,
      this.identity.profile$.value,
      this.identity.directoryUsers$.value,
      this.role === 'Manager' ? this.drill : undefined,
    );
  }

  get teamDocs(): DocumentationDocument[] {
    return this.teamRequests
      .map((r) => mapRequestToGeneratedDocument(r))
      .filter((d): d is DocumentationDocument => d !== null);
  }

  get memberCount(): number {
    return new Set(
      [...this.teamRequests.map((r) => r.employeeId), ...this.teamDocs.map((d) => d.employeeId)].filter(Boolean),
    ).size;
  }

  readonly statsDef = [
    { key: 'req', label: 'Demandes équipe', icon: 'users', color: 'text-blue-500', bg: 'bg-blue-500/10' },
    { key: 'pend', label: 'En attente de validation', icon: 'clock', color: 'text-amber-500', bg: 'bg-amber-500/10' },
    { key: 'gen', label: 'Documents générés (équipe)', icon: 'check-circle-2', color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
    { key: 'mem', label: 'Membres de l’équipe', icon: 'user', color: 'text-indigo-500', bg: 'bg-indigo-500/10' },
  ];

  statValue(key: string): number {
    switch (key) {
      case 'req':
        return this.teamRequests.length;
      case 'pend':
        return this.teamRequests.filter((r) => r.status === 'Pending').length;
      case 'gen':
        return this.teamDocs.length;
      case 'mem':
        return this.memberCount;
      default:
        return 0;
    }
  }

  goTeamDocs(): void {
    this.nav.navigateToTab('team-docs');
  }

  goTeamRequests(): void {
    this.nav.navigateToTab('team-requests');
  }

  previewRequests(): DocumentationRequest[] {
    return this.teamRequests.slice(0, 4);
  }
}

<div class="space-y-8">
  @if (role === 'Manager') {
    <app-doc-drill-bar [role]="role"></app-doc-drill-bar>
  }
  @if (loading) {
    <p class="text-slate-400 text-sm">Chargement…</p>
  } @else if (error) {
    <p class="text-red-400 text-sm">{{ error }}</p>
  }
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    @for (stat of statsDef; track stat.key; let i = $index) {
      <div
        class="card-navy p-6 flex items-center justify-between doc-animate-in"
        [class.doc-stagger-0]="i === 0"
        [class.doc-stagger-1]="i === 1"
        [class.doc-stagger-2]="i === 2"
        [class.doc-stagger-3]="i === 3"
      >
        <div>
          <p class="text-sm text-slate-400 font-medium mb-1">{{ stat.label }}</p>
          <h3 class="text-3xl font-bold text-white">{{ statValue(stat.key) }}</h3>
        </div>
        <div class="w-12 h-12 rounded-xl flex items-center justify-center" [ngClass]="stat.bg">
          <app-doc-icon [name]="stat.icon" [klass]="'w-6 h-6 ' + stat.color"></app-doc-icon>
        </div>
      </div>
    }
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
    <div class="lg:col-span-1 space-y-6">
      <h3 class="text-lg font-semibold text-white">Actions rapides</h3>
      <div class="space-y-3">
        <button
          type="button"
          (click)="goTeamDocs()"
          class="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
        >
          <div
            class="w-10 h-10 bg-blue-600/10 rounded-lg flex items-center justify-center group-hover:bg-blue-600 transition-colors"
          >
            <app-doc-icon name="users" klass="w-5 h-5 text-blue-500 group-hover:text-white"></app-doc-icon>
          </div>
          <div class="text-left">
            <p class="text-sm font-semibold text-white">Documents équipe</p>
            <p class="text-xs text-slate-500">Fichiers de l’équipe</p>
          </div>
          <app-doc-icon name="chevron-right" klass="ml-auto w-4 h-4 text-slate-600"></app-doc-icon>
        </button>
        <button
          type="button"
          (click)="goTeamRequests()"
          class="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
        >
          <div
            class="w-10 h-10 bg-amber-600/10 rounded-lg flex items-center justify-center group-hover:bg-amber-600 transition-colors"
          >
            <app-doc-icon name="clipboard-list" klass="w-5 h-5 text-amber-500 group-hover:text-white"></app-doc-icon>
          </div>
          <div class="text-left">
            <p class="text-sm font-semibold text-white">Demandes équipe</p>
            <p class="text-xs text-slate-500">Demandes en attente</p>
          </div>
          <app-doc-icon name="chevron-right" klass="ml-auto w-4 h-4 text-slate-600"></app-doc-icon>
        </button>
      </div>
    </div>

    <div class="lg:col-span-2 space-y-6">
      <div class="flex items-center justify-between">
        <h3 class="text-lg font-semibold text-white">Demandes récentes (équipe)</h3>
        <button
          type="button"
          (click)="goTeamRequests()"
          class="text-sm text-blue-500 hover:text-blue-400 font-medium"
        >
          Tout voir
        </button>
      </div>
      <div class="card-navy overflow-hidden">
        <table class="w-full text-left border-collapse">
          <thead>
            <tr class="bg-navy-800/50 border-b border-navy-800">
              <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                Collaborateur
              </th>
              <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Type</th>
              <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Date</th>
              <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Statut</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-navy-800">
            @if (!loading && !error && previewRequests().length === 0) {
              <tr>
                <td colspan="4" class="px-6 py-8 text-center text-sm text-slate-500">Aucune demande.</td>
              </tr>
            }
            @for (req of previewRequests(); track req.id) {
              <tr class="hover:bg-navy-800/30 transition-colors">
                <td class="px-6 py-4">
                  <div class="flex items-center gap-3">
                    <div class="w-8 h-8 bg-navy-800 rounded-full flex items-center justify-center">
                      <app-doc-icon name="user" klass="w-4 h-4 text-slate-400"></app-doc-icon>
                    </div>
                    <span class="text-sm font-medium text-slate-200">{{ req.employeeName }}</span>
                  </div>
                </td>
                <td class="px-6 py-4 text-sm text-slate-300">{{ req.type }}</td>
                <td class="px-6 py-4 text-sm text-slate-400">{{ req.requestDate }}</td>
                <td class="px-6 py-4">
                  <app-status-badge [status]="req.status"></app-status-badge>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/dashboards/ManagerDashboard.tsx
import React from 'react';
import { motion } from 'motion/react';
import { ICONS, Role } from '../../types';
import { MOCK_REQUESTS, MOCK_TEAM_DOCS } from '../../mockData';
import { Badge } from '../Badge';
import { filterByEmployeeScope } from '../../lib/documentationFilters';
import { useDocumentationHierarchyDrill } from '../../contexts/DocumentationHierarchyDrillContext';
import { DocDrillBar } from '../DocDrillBar';

interface Props {
  setActiveTab: (tab: string) => void;
  role: Role;
}

export const ManagerDashboard: React.FC<Props> = ({ setActiveTab, role }) => {
  const { drill } = useDocumentationHierarchyDrill();
  const teamRequests = filterByEmployeeScope(MOCK_REQUESTS, role, role === 'Manager' ? drill : undefined);
  const teamDocs = filterByEmployeeScope(MOCK_TEAM_DOCS, role, role === 'Manager' ? drill : undefined);
  const memberCount = new Set(
    [...teamRequests.map((r) => r.employeeId), ...teamDocs.map((d) => d.employeeId)].filter(Boolean),
  ).size;

  const stats = [
    {
      label: 'Demandes équipe',
      value: teamRequests.length,
      icon: ICONS.Team,
      color: 'text-blue-500',
      bg: 'bg-blue-500/10',
    },
    {
      label: 'En attente de validation',
      value: teamRequests.filter((r) => r.status === 'Pending').length,
      icon: ICONS.Clock,
      color: 'text-amber-500',
      bg: 'bg-amber-500/10',
    },
    {
      label: 'Générés cette semaine',
      value: teamDocs.filter((d) => d.status === 'Generated').length,
      icon: ICONS.Check,
      color: 'text-emerald-500',
      bg: 'bg-emerald-500/10',
    },
    {
      label: 'Membres de l’équipe',
      value: memberCount,
      icon: ICONS.User,
      color: 'text-indigo-500',
      bg: 'bg-indigo-500/10',
    },
  ];

  return (
    <div className="space-y-8">
      {role === 'Manager' && <DocDrillBar role={role} />}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, i) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="card-navy p-6 flex items-center justify-between"
          >
            <div>
              <p className="text-sm text-slate-400 font-medium mb-1">{stat.label}</p>
              <h3 className="text-3xl font-bold text-white">{stat.value}</h3>
            </div>
            <div className={`w-12 h-12 ${stat.bg} rounded-xl flex items-center justify-center`}>
              <stat.icon className={`w-6 h-6 ${stat.color}`} />
            </div>
          </motion.div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-1 space-y-6">
          <h3 className="text-lg font-semibold text-white">Actions rapides</h3>
          <div className="space-y-3">
            <button
              onClick={() => setActiveTab('team-docs')}
              className="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
            >
              <div className="w-10 h-10 bg-blue-600/10 rounded-lg flex items-center justify-center group-hover:bg-blue-600 transition-colors">
                <ICONS.Team className="w-5 h-5 text-blue-500 group-hover:text-white" />
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-white">Documents équipe</p>
                <p className="text-xs text-slate-500">Fichiers de l’équipe</p>
              </div>
              <ICONS.ChevronRight className="ml-auto w-4 h-4 text-slate-600" />
            </button>
            <button
              onClick={() => setActiveTab('team-requests')}
              className="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
            >
              <div className="w-10 h-10 bg-amber-600/10 rounded-lg flex items-center justify-center group-hover:bg-amber-600 transition-colors">
                <ICONS.ClipboardList className="w-5 h-5 text-amber-500 group-hover:text-white" />
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-white">Demandes équipe</p>
                <p className="text-xs text-slate-500">Demandes en attente</p>
              </div>
              <ICONS.ChevronRight className="ml-auto w-4 h-4 text-slate-600" />
            </button>
          </div>
        </div>

        <div className="lg:col-span-2 space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold text-white">Demandes récentes (équipe)</h3>
            <button
              onClick={() => setActiveTab('team-requests')}
              className="text-sm text-blue-500 hover:text-blue-400 font-medium"
            >
              Tout voir
            </button>
          </div>
          <div className="card-navy overflow-hidden">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-navy-800/50 border-b border-navy-800">
                  <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Collaborateur
                  </th>
                  <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Type
                  </th>
                  <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Date
                  </th>
                  <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Statut
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-navy-800">
                {teamRequests.slice(0, 4).map((req) => (
                  <tr key={req.id} className="hover:bg-navy-800/30 transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 bg-navy-800 rounded-full flex items-center justify-center">
                          <ICONS.User className="w-4 h-4 text-slate-400" />
                        </div>
                        <span className="text-sm font-medium text-slate-200">
                          {req.employeeName}
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm text-slate-300">{req.type}</td>
                    <td className="px-6 py-4 text-sm text-slate-400">{req.requestDate}</td>
                    <td className="px-6 py-4">
                      <Badge status={req.status} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};
