// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/components/pilote-dashboard/pilote-dashboard.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { forkJoin, Subscription } from 'rxjs';

import { DocumentationIdentityService } from '../../../core/services/documentation-identity.service';
import type { DocumentationRequest } from '../../interfaces/documentation-entities';
import { switchMapOnDocumentationContext } from '../../lib/documentation-context-refresh';
import { mapDocumentRequestDto } from '../../lib/documentation-dto-mappers';
import { DocumentationApiService } from '../../services/documentation-api.service';
import { DocumentationNavigationService } from '../../services/documentation-navigation.service';
import { DocIconComponent } from '../doc-icon/doc-icon.component';
import { StatusBadgeComponent } from '../status-badge/status-badge.component';

@Component({
  selector: 'app-pilote-dashboard',
  standalone: true,
  imports: [CommonModule, DocIconComponent, StatusBadgeComponent],
  templateUrl: './pilote-dashboard.component.html',
  styleUrl: './pilote-dashboard.component.scss',
})
export class PiloteDashboardComponent implements OnInit, OnDestroy {
  private readonly role = 'Pilote' as const;
  private sub = new Subscription();

  loading = true;
  error: string | null = null;
  private scopedReqs: DocumentationRequest[] = [];
  private myDocsCount = 0;

  stats: Array<{
    label: string;
    value: number;
    icon: string;
    color: string;
    bg: string;
  }> = [];

  recentRows: DocumentationRequest[] = [];

  constructor(
    private readonly api: DocumentationApiService,
    private readonly nav: DocumentationNavigationService,
    private readonly identity: DocumentationIdentityService,
  ) {}

  ngOnInit(): void {
    this.sub.add(
      switchMapOnDocumentationContext(this.identity, () =>
        forkJoin({
          submitted: this.api.getAllMyDocumentRequests(),
          assigned: this.api.getAllAssignedDocumentRequests(),
        }),
      ).subscribe({
        next: ({ submitted, assigned }) => {
          const submittedUi = submitted.map(mapDocumentRequestDto);
          const assignedUi = assigned.map(mapDocumentRequestDto);
          this.scopedReqs = submittedUi;
          const mergedByInternal = new Map<string, DocumentationRequest>();
          for (const r of [...submittedUi, ...assignedUi]) {
            mergedByInternal.set(r.internalId, r);
          }
          this.myDocsCount = [...mergedByInternal.values()].filter((r) => r.status === 'Generated').length;
          const active = submittedUi.filter((r) => r.status === 'Pending').length;
          const approved = submittedUi.filter((r) => r.status === 'Approved').length;
          const total = submittedUi.length;
          this.stats = [
            {
              label: 'Mes documents',
              value: this.myDocsCount,
              icon: 'file-text',
              color: 'text-blue-500',
              bg: 'bg-blue-500/10',
            },
            {
              label: 'Demandes actives',
              value: active,
              icon: 'clock',
              color: 'text-amber-500',
              bg: 'bg-amber-500/10',
            },
            {
              label: 'Approuvées',
              value: approved,
              icon: 'check-circle-2',
              color: 'text-emerald-500',
              bg: 'bg-emerald-500/10',
            },
            {
              label: 'Total des demandes',
              value: total,
              icon: 'history',
              color: 'text-indigo-500',
              bg: 'bg-indigo-500/10',
            },
          ];
          this.recentRows = [...submittedUi]
            .sort((a, b) => b.requestDate.localeCompare(a.requestDate))
            .slice(0, 4);
          this.loading = false;
          this.error = null;
        },
        error: () => {
          this.scopedReqs = [];
          this.stats = [];
          this.recentRows = [];
          this.loading = false;
          this.error = 'Impossible de charger les demandes. Vérifiez l’API et la base de données.';
        },
      }),
    );
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }

  goRequest(): void {
    this.nav.navigateToTab('request');
  }

  goMyDocs(): void {
    this.nav.navigateToTab('my-docs');
  }

  goTracking(): void {
    this.nav.navigateToTab('tracking');
  }
}

<div class="space-y-8">
  @if (loading) {
    <p class="text-slate-400 text-sm">Chargement des indicateurs…</p>
  } @else if (error) {
    <p class="text-red-400 text-sm">{{ error }}</p>
  }

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    @for (stat of stats; track stat.label; let i = $index) {
      <div
        class="card-navy p-6 flex items-center justify-between doc-animate-in"
        [class.doc-stagger-0]="i === 0"
        [class.doc-stagger-1]="i === 1"
        [class.doc-stagger-2]="i === 2"
        [class.doc-stagger-3]="i === 3"
      >
        <div>
          <p class="text-sm text-slate-400 font-medium mb-1">{{ stat.label }}</p>
          <h3 class="text-3xl font-bold text-white">{{ stat.value }}</h3>
        </div>
        <div class="w-12 h-12 rounded-xl flex items-center justify-center" [ngClass]="stat.bg">
          <app-doc-icon [name]="stat.icon" [klass]="'w-6 h-6 ' + stat.color"></app-doc-icon>
        </div>
      </div>
    }
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
    <div class="lg:col-span-1 space-y-6">
      <h3 class="text-lg font-semibold text-white">Actions rapides</h3>
      <div class="space-y-3">
        <button
          type="button"
          (click)="goRequest()"
          class="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
        >
          <div
            class="w-10 h-10 bg-blue-600/10 rounded-lg flex items-center justify-center group-hover:bg-blue-600 transition-colors"
          >
            <app-doc-icon name="plus-circle" klass="w-5 h-5 text-blue-500 group-hover:text-white"></app-doc-icon>
          </div>
          <div class="text-left">
            <p class="text-sm font-semibold text-white">Demander un document</p>
            <p class="text-xs text-slate-500">Nouvelle demande RH</p>
          </div>
          <app-doc-icon name="chevron-right" klass="ml-auto w-4 h-4 text-slate-600"></app-doc-icon>
        </button>
        <button
          type="button"
          (click)="goMyDocs()"
          class="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
        >
          <div
            class="w-10 h-10 bg-emerald-600/10 rounded-lg flex items-center justify-center group-hover:bg-emerald-600 transition-colors"
          >
            <app-doc-icon name="file-text" klass="w-5 h-5 text-emerald-500 group-hover:text-white"></app-doc-icon>
          </div>
          <div class="text-left">
            <p class="text-sm font-semibold text-white">Mes documents</p>
            <p class="text-xs text-slate-500">Accéder aux fichiers générés</p>
          </div>
          <app-doc-icon name="chevron-right" klass="ml-auto w-4 h-4 text-slate-600"></app-doc-icon>
        </button>
      </div>
    </div>

    <div class="lg:col-span-2 space-y-6">
      <div class="flex items-center justify-between">
        <h3 class="text-lg font-semibold text-white">Demandes récentes</h3>
        <button
          type="button"
          (click)="goTracking()"
          class="text-sm text-blue-500 hover:text-blue-400 font-medium"
        >
          Tout voir
        </button>
      </div>
      <div class="card-navy overflow-hidden">
        <table class="w-full text-left border-collapse">
          <thead>
            <tr class="bg-navy-800/50 border-b border-navy-800">
              <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Type</th>
              <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Date</th>
              <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Statut</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-navy-800">
            @if (!loading && !error && recentRows.length === 0) {
              <tr>
                <td colspan="3" class="px-6 py-8 text-center text-sm text-slate-500">Aucune demande pour le moment.</td>
              </tr>
            }
            @for (req of recentRows; track req.id) {
              <tr class="hover:bg-navy-800/30 transition-colors">
                <td class="px-6 py-4">
                  <div class="flex items-center gap-3">
                    <div class="w-8 h-8 bg-navy-800 rounded flex items-center justify-center">
                      <app-doc-icon name="file-text" klass="w-4 h-4 text-slate-400"></app-doc-icon>
                    </div>
                    <span class="text-sm font-medium text-slate-200">{{ req.type }}</span>
                  </div>
                </td>
                <td class="px-6 py-4 text-sm text-slate-400">{{ req.requestDate }}</td>
                <td class="px-6 py-4">
                  <app-status-badge [status]="req.status"></app-status-badge>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/dashboards/PiloteDashboard.tsx
import React from 'react';
import { motion } from 'motion/react';
import { ICONS, Role } from '../../types';
import { MOCK_DOCUMENTS, MOCK_REQUESTS } from '../../mockData';
import { Badge } from '../Badge';
import { filterByEmployeeScope } from '../../lib/documentationFilters';

interface Props {
  setActiveTab: (tab: string) => void;
  role: Role;
}

export const PiloteDashboard: React.FC<Props> = ({ setActiveTab, role }) => {
  const myDocs = filterByEmployeeScope(MOCK_DOCUMENTS, role);
  const myReqs = filterByEmployeeScope(MOCK_REQUESTS, role);
  const stats = [
    {
      label: 'Mes documents',
      value: myDocs.length,
      icon: ICONS.Documents,
      color: 'text-blue-500',
      bg: 'bg-blue-500/10',
    },
    {
      label: 'Demandes actives',
      value: myReqs.filter((r) => r.status === 'Pending').length,
      icon: ICONS.Clock,
      color: 'text-amber-500',
      bg: 'bg-amber-500/10',
    },
    {
      label: 'Approuvées',
      value: myReqs.filter((r) => r.status === 'Approved').length,
      icon: ICONS.Check,
      color: 'text-emerald-500',
      bg: 'bg-emerald-500/10',
    },
    {
      label: 'Total des demandes',
      value: myReqs.length,
      icon: ICONS.History,
      color: 'text-indigo-500',
      bg: 'bg-indigo-500/10',
    },
  ];

  return (
    <div className="space-y-8">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, i) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="card-navy p-6 flex items-center justify-between"
          >
            <div>
              <p className="text-sm text-slate-400 font-medium mb-1">{stat.label}</p>
              <h3 className="text-3xl font-bold text-white">{stat.value}</h3>
            </div>
            <div className={`w-12 h-12 ${stat.bg} rounded-xl flex items-center justify-center`}>
              <stat.icon className={`w-6 h-6 ${stat.color}`} />
            </div>
          </motion.div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-1 space-y-6">
          <h3 className="text-lg font-semibold text-white">Actions rapides</h3>
          <div className="space-y-3">
            <button
              onClick={() => setActiveTab('request')}
              className="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
            >
              <div className="w-10 h-10 bg-blue-600/10 rounded-lg flex items-center justify-center group-hover:bg-blue-600 transition-colors">
                <ICONS.Request className="w-5 h-5 text-blue-500 group-hover:text-white" />
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-white">Demander un document</p>
                <p className="text-xs text-slate-500">Nouvelle demande RH</p>
              </div>
              <ICONS.ChevronRight className="ml-auto w-4 h-4 text-slate-600" />
            </button>
            <button
              onClick={() => setActiveTab('my-docs')}
              className="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
            >
              <div className="w-10 h-10 bg-emerald-600/10 rounded-lg flex items-center justify-center group-hover:bg-emerald-600 transition-colors">
                <ICONS.Documents className="w-5 h-5 text-emerald-500 group-hover:text-white" />
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-white">Mes documents</p>
                <p className="text-xs text-slate-500">Accéder aux fichiers générés</p>
              </div>
              <ICONS.ChevronRight className="ml-auto w-4 h-4 text-slate-600" />
            </button>
          </div>
        </div>

        <div className="lg:col-span-2 space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold text-white">Demandes récentes</h3>
            <button
              onClick={() => setActiveTab('tracking')}
              className="text-sm text-blue-500 hover:text-blue-400 font-medium"
            >
              Tout voir
            </button>
          </div>
          <div className="card-navy overflow-hidden">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-navy-800/50 border-b border-navy-800">
                  <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Type
                  </th>
                  <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Date
                  </th>
                  <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Statut
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-navy-800">
                {MOCK_REQUESTS.slice(0, 4).map((req) => (
                  <tr key={req.id} className="hover:bg-navy-800/30 transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 bg-navy-800 rounded flex items-center justify-center">
                          <ICONS.Documents className="w-4 h-4 text-slate-400" />
                        </div>
                        <span className="text-sm font-medium text-slate-200">{req.type}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm text-slate-400">{req.requestDate}</td>
                    <td className="px-6 py-4">
                      <Badge status={req.status} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};
