// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/admin/AdminStoragePage.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { Role } from '../../types';
import { ICONS } from '../../types';
import { AdminStorageConfig, AdminStorageType } from '../../adminDocumentation/documentAdminModels';
import {
  getStorageConfig,
  resetStorageConfig,
  saveStorageConfig,
} from '../../adminDocumentation/documentAdminService';
import { AdminShell } from './AdminShell';
import { AdminToggle } from './AdminToggle';

function maskAccessKey(value: string) {
  const v = value ?? '';
  if (v.length <= 8) return '********';
  return `${v.slice(0, 4)}****${v.slice(-4)}`;
}

export const AdminStoragePage: React.FC<{ role: Role }> = ({ role }) => {
  const isAdmin = role === 'Admin';

  const [loading, setLoading] = useState(true);
  const [draft, setDraft] = useState<AdminStorageConfig | null>(null);
  const [accessKeyInput, setAccessKeyInput] = useState('');
  const [revealKey, setRevealKey] = useState(false);

  const [saving, setSaving] = useState(false);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const storageTypes: AdminStorageType[] = useMemo(() => ['Local', 'Cloud'], []);

  const reload = async () => {
    const cfg = await getStorageConfig();
    setDraft(cfg);
    setAccessKeyInput('');
    setRevealKey(false);
  };

  useEffect(() => {
    let mounted = true;
    (async () => {
      try {
        await reload();
      } finally {
        if (!mounted) return;
        setLoading(false);
      }
    })();
    return () => {
      mounted = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const validate = (): Record<string, string> => {
    const e: Record<string, string> = {};
    if (!draft) return e;

    if (!draft.apiUrl.trim()) e.apiUrl = "URL API requise.";
    if (draft.storageType === 'Cloud') {
      if (!draft.bucketName.trim()) e.bucketName = "Nom du bucket requis (Cloud).";
      if (!draft.region.trim()) e.region = 'Région requise (Cloud).';
    }
    return e;
  };

  const onSave = async () => {
    if (!draft) return;
    setErrors({});
    setSuccessMessage(null);
    const e = validate();
    setErrors(e);
    if (Object.keys(e).length > 0) return;

    setSaving(true);
    try {
      const next: AdminStorageConfig = {
        ...draft,
        accessKey: accessKeyInput.trim() ? accessKeyInput.trim() : draft.accessKey,
      };
      await saveStorageConfig(next);
      setSuccessMessage('Configuration de stockage sauvegardée.');
      await reload();
    } finally {
      setSaving(false);
    }
  };

  const onReset = async () => {
    setSuccessMessage(null);
    setErrors({});
    setLoading(true);
    try {
      await resetStorageConfig();
      await reload();
    } finally {
      setLoading(false);
    }
  };

  if (!isAdmin) {
    return (
      <AdminShell title="Storage Configuration" description="Accès refusé pour ce rôle." icon={ICONS.Storage}>
        <div className="card-navy p-6">
          <p className="text-slate-300">Seul le rôle `Admin` peut modifier la configuration de stockage.</p>
        </div>
      </AdminShell>
    );
  }

  if (loading || !draft) {
    return (
      <AdminShell title="Storage Configuration" description="Chargement de la configuration…" icon={ICONS.Storage}>
        <div className="card-navy p-6">
          <p className="text-slate-300">Veuillez patienter.</p>
        </div>
      </AdminShell>
    );
  }

  const maskedKey = maskAccessKey(draft.accessKey);

  return (
    <AdminShell
      title="Configuration du stockage"
      description="Définissez le type de stockage (Local/Cloud), les endpoints et les options DMS"
      icon={ICONS.Storage}
    >
      <div className="card-navy p-6 space-y-6">
        {successMessage && (
          <div className="px-4 py-3 rounded-lg bg-emerald-500/10 text-emerald-300 border border-emerald-500/20">
            {successMessage}
          </div>
        )}

        <div className="flex flex-col md:flex-row items-stretch md:items-center justify-between gap-3">
          <div>
            <h4 className="text-white font-bold text-lg">{draft.storageType} storage</h4>
            <p className="text-sm text-slate-500 mt-1">Les secrets sont stockés côté service/mock, affichés masqués en UI.</p>
          </div>
          <div className="flex gap-3 flex-wrap">
            <button
              onClick={onSave}
              disabled={saving}
              className={`px-6 py-3 rounded-lg font-bold text-white transition-all ${
                saving ? 'bg-slate-600 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-500 shadow-lg shadow-blue-600/20'
              }`}
              type="button"
            >
              {saving ? 'Sauvegarde…' : 'Sauvegarder'}
            </button>
            <button
              onClick={onReset}
              disabled={saving}
              className="px-6 py-3 rounded-lg font-bold text-slate-200 border border-navy-800 hover:bg-navy-800/50 transition-all"
              type="button"
            >
              Réinitialiser
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-4">
            <div>
              <label className="text-sm font-semibold text-white">Type de stockage</label>
              <select
                value={draft.storageType}
                onChange={(e) => setDraft({ ...draft, storageType: e.target.value as AdminStorageType })}
                className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
              >
                {storageTypes.map((t) => (
                  <option key={t} value={t}>
                    {t}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="text-sm font-semibold text-white">URL API</label>
              <input
                value={draft.apiUrl}
                onChange={(e) => setDraft({ ...draft, apiUrl: e.target.value })}
                className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
              />
              {errors.apiUrl && <p className="text-xs text-red-400 mt-1">{errors.apiUrl}</p>}
            </div>

            <div>
              <label className="text-sm font-semibold text-white">Nom du bucket</label>
              <input
                value={draft.bucketName}
                onChange={(e) => setDraft({ ...draft, bucketName: e.target.value })}
                disabled={draft.storageType !== 'Cloud'}
                className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500 disabled:opacity-60"
              />
              {errors.bucketName && <p className="text-xs text-red-400 mt-1">{errors.bucketName}</p>}
            </div>

            <div>
              <label className="text-sm font-semibold text-white">Région</label>
              <input
                value={draft.region}
                onChange={(e) => setDraft({ ...draft, region: e.target.value })}
                disabled={draft.storageType !== 'Cloud'}
                className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500 disabled:opacity-60"
              />
              {errors.region && <p className="text-xs text-red-400 mt-1">{errors.region}</p>}
            </div>
          </div>

          <div className="space-y-4">
            <div className="border border-navy-800 rounded-xl p-4 bg-navy-900/30">
              <h4 className="text-sm font-bold text-white">Clé d’accès</h4>
              <p className="text-xs text-slate-500 mt-1">
                Affichage masqué en UI. Pour remplacer le secret, saisissez une nouvelle valeur.
              </p>

              <div className="mt-4 flex items-center justify-between gap-4">
                <div className="text-sm text-slate-200">
                  Secret actuel: <span className="font-mono text-slate-100">{revealKey ? draft.accessKey : maskedKey}</span>
                </div>
                <button
                  type="button"
                  onClick={() => setRevealKey((v) => !v)}
                  className="px-3 py-2 text-xs font-semibold text-blue-500 hover:text-blue-400 border border-blue-500/20 hover:bg-blue-500/10 rounded-lg transition-all"
                >
                  {revealKey ? 'Masquer' : 'Révéler'}
                </button>
              </div>

              <div className="mt-4">
                <label className="text-sm font-semibold text-white">Nouveau secret (optionnel)</label>
                <input
                  type="password"
                  value={accessKeyInput}
                  onChange={(e) => setAccessKeyInput(e.target.value)}
                  placeholder="******"
                  className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
                />
                <p className="text-xs text-slate-500 mt-1">
                  Laisser vide conserve la valeur actuelle (mock).
                </p>
              </div>
            </div>

            <div className="border border-navy-800 rounded-xl p-4">
              <h4 className="text-sm font-bold text-white mb-3">Options</h4>
              <div className="space-y-3">
                <AdminToggle
                  checked={draft.backupEnabled}
                  onChange={(next) => setDraft({ ...draft, backupEnabled: next })}
                  label="Activer backup"
                />
                <AdminToggle
                  checked={draft.compressionEnabled}
                  onChange={(next) => setDraft({ ...draft, compressionEnabled: next })}
                  label="Activer compression"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </AdminShell>
  );
};

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/pages/admin-storage-page.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';

import type { DocumentationRole } from '../interfaces/documentation-role';
import type { AdminStorageConfig, AdminStorageType } from '../models/document-admin.models';
import { AdminShellComponent } from '../components/admin-shell/admin-shell.component';
import { AdminToggleComponent } from '../components/admin-toggle/admin-toggle.component';
import { DocumentAdminService } from '../services/document-admin.service';
import { DocumentationNavigationService } from '../services/documentation-navigation.service';

function maskAccessKey(value: string): string {
  const v = value ?? '';
  if (v.length <= 8) return '********';
  return `${v.slice(0, 4)}****${v.slice(-4)}`;
}

@Component({
  standalone: true,
  selector: 'app-admin-storage-page',
  imports: [CommonModule, FormsModule, AdminShellComponent, AdminToggleComponent],
  templateUrl: './admin-storage-page.component.html',
})
export class AdminStoragePageComponent implements OnInit {
  readonly role$ = this.nav.role$;
  readonly storageTypes: AdminStorageType[] = ['Local', 'Cloud'];

  loading = true;
  draft: AdminStorageConfig | null = null;
  accessKeyInput = '';
  revealKey = false;
  saving = false;
  successMessage: string | null = null;
  errors: Record<string, string> = {};

  constructor(
    private readonly nav: DocumentationNavigationService,
    private readonly admin: DocumentAdminService
  ) {}

  ngOnInit(): void {
    void this.reload();
  }

  get maskedKey(): string {
    return this.draft ? maskAccessKey(this.draft.accessKey) : '';
  }

  async reload(): Promise<void> {
    const cfg = await this.admin.getStorageConfig();
    this.draft = cfg;
    this.accessKeyInput = '';
    this.revealKey = false;
    this.loading = false;
  }

  validate(): Record<string, string> {
    const e: Record<string, string> = {};
    if (!this.draft) return e;
    if (!this.draft.apiUrl.trim()) e['apiUrl'] = 'URL API requise.';
    if (this.draft.storageType === 'Cloud') {
      if (!this.draft.bucketName.trim()) e['bucketName'] = 'Nom du bucket requis (Cloud).';
      if (!this.draft.region.trim()) e['region'] = 'Région requise (Cloud).';
    }
    return e;
  }

  async onSave(): Promise<void> {
    if (!this.draft) return;
    this.errors = {};
    this.successMessage = null;
    const e = this.validate();
    this.errors = e;
    if (Object.keys(e).length > 0) return;

    this.saving = true;
    try {
      const next: AdminStorageConfig = {
        ...this.draft,
        accessKey: this.accessKeyInput.trim() ? this.accessKeyInput.trim() : this.draft.accessKey,
      };
      await this.admin.saveStorageConfig(next);
      this.successMessage = 'Configuration de stockage sauvegardée.';
      this.loading = true;
      await this.reload();
    } finally {
      this.saving = false;
    }
  }

  async onReset(): Promise<void> {
    this.successMessage = null;
    this.errors = {};
    this.loading = true;
    try {
      await this.admin.resetStorageConfig();
      await this.reload();
    } finally {
      this.loading = false;
    }
  }

  isAdmin(role: DocumentationRole): boolean {
    return role === 'Admin';
  }

  patchDraft(partial: Partial<AdminStorageConfig>): void {
    if (!this.draft) return;
    this.draft = { ...this.draft, ...partial };
  }

  onStorageTypeChange(v: string): void {
    this.patchDraft({ storageType: v as AdminStorageType });
  }

  toggleReveal(): void {
    this.revealKey = !this.revealKey;
  }
}

@if (role$ | async; as role) {
  @if (!isAdmin(role)) {
    <app-admin-shell title="Storage Configuration" description="Accès refusé pour ce rôle." iconName="hard-drive">
      <div class="card-navy p-6">
        <p class="text-slate-300">Seul le rôle `Admin` peut modifier la configuration de stockage.</p>
      </div>
    </app-admin-shell>
  } @else if (loading || !draft) {
    <app-admin-shell title="Storage Configuration" description="Chargement de la configuration…" iconName="hard-drive">
      <div class="card-navy p-6">
        <p class="text-slate-300">Veuillez patienter.</p>
      </div>
    </app-admin-shell>
  } @else {
    <app-admin-shell
      title="Configuration du stockage"
      description="Définissez le type de stockage (Local/Cloud), les endpoints et les options DMS"
      iconName="hard-drive"
    >
      <div class="card-navy p-6 space-y-6">
        @if (successMessage) {
          <div class="px-4 py-3 rounded-lg bg-emerald-500/10 text-emerald-300 border border-emerald-500/20">
            {{ successMessage }}
          </div>
        }

        <div class="flex flex-col md:flex-row items-stretch md:items-center justify-between gap-3">
          <div>
            <h4 class="text-white font-bold text-lg">{{ draft.storageType }} storage</h4>
            <p class="text-sm text-slate-500 mt-1">Les secrets sont stockés côté service, affichés masqués en UI.</p>
          </div>
          <div class="flex gap-3 flex-wrap">
            <button
              type="button"
              (click)="onSave()"
              [disabled]="saving"
              class="px-6 py-3 rounded-lg font-bold text-white transition-all"
              [ngClass]="
                saving ? 'bg-slate-600 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-500 shadow-lg shadow-blue-600/20'
              "
            >
              {{ saving ? 'Sauvegarde…' : 'Sauvegarder' }}
            </button>
            <button
              type="button"
              (click)="onReset()"
              [disabled]="saving"
              class="px-6 py-3 rounded-lg font-bold text-slate-200 border border-navy-800 hover:bg-navy-800/50 transition-all"
            >
              Réinitialiser
            </button>
          </div>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div class="space-y-4">
            <div>
              <label class="text-sm font-semibold text-white">Type de stockage</label>
              <select
                [ngModel]="draft.storageType"
                (ngModelChange)="onStorageTypeChange($event)"
                class="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
              >
                @for (t of storageTypes; track t) {
                  <option [value]="t">{{ t }}</option>
                }
              </select>
            </div>

            <div>
              <label class="text-sm font-semibold text-white">URL API</label>
              <input
                [(ngModel)]="draft.apiUrl"
                class="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
              />
              @if (errors['apiUrl']) {
                <p class="text-xs text-red-400 mt-1">{{ errors['apiUrl'] }}</p>
              }
            </div>

            <div>
              <label class="text-sm font-semibold text-white">Nom du bucket</label>
              <input
                [(ngModel)]="draft.bucketName"
                [disabled]="draft.storageType !== 'Cloud'"
                class="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500 disabled:opacity-60"
              />
              @if (errors['bucketName']) {
                <p class="text-xs text-red-400 mt-1">{{ errors['bucketName'] }}</p>
              }
            </div>

            <div>
              <label class="text-sm font-semibold text-white">Région</label>
              <input
                [(ngModel)]="draft.region"
                [disabled]="draft.storageType !== 'Cloud'"
                class="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500 disabled:opacity-60"
              />
              @if (errors['region']) {
                <p class="text-xs text-red-400 mt-1">{{ errors['region'] }}</p>
              }
            </div>
          </div>

          <div class="space-y-4">
            <div class="border border-navy-800 rounded-xl p-4 bg-navy-900/30">
              <h4 class="text-sm font-bold text-white">Clé d’accès</h4>
              <p class="text-xs text-slate-500 mt-1">Affichage masqué en UI. Pour remplacer le secret, saisissez une nouvelle valeur.</p>

              <div class="mt-4 flex items-center justify-between gap-4">
                <div class="text-sm text-slate-200">
                  Secret actuel:
                  <span class="font-mono text-slate-100">{{ revealKey ? draft.accessKey : maskedKey }}</span>
                </div>
                <button
                  type="button"
                  (click)="toggleReveal()"
                  class="px-3 py-2 text-xs font-semibold text-blue-500 hover:text-blue-400 border border-blue-500/20 hover:bg-blue-500/10 rounded-lg transition-all"
                >
                  {{ revealKey ? 'Masquer' : 'Révéler' }}
                </button>
              </div>

              <div class="mt-4">
                <label class="text-sm font-semibold text-white">Nouveau secret (optionnel)</label>
                <input
                  type="password"
                  [(ngModel)]="accessKeyInput"
                  placeholder="******"
                  class="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
                />
                <p class="text-xs text-slate-500 mt-1">Laisser vide conserve la valeur actuelle.</p>
              </div>
            </div>

            <div class="border border-navy-800 rounded-xl p-4">
              <h4 class="text-sm font-bold text-white mb-3">Options</h4>
              <div class="space-y-3">
                <app-admin-toggle
                  [checked]="draft.backupEnabled"
                  (checkedChange)="patchDraft({ backupEnabled: $event })"
                  label="Activer backup"
                ></app-admin-toggle>
                <app-admin-toggle
                  [checked]="draft.compressionEnabled"
                  (checkedChange)="patchDraft({ compressionEnabled: $event })"
                  label="Activer compression"
                ></app-admin-toggle>
              </div>
            </div>
          </div>
        </div>
      </div>
    </app-admin-shell>
  }
}
