// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/pages/admin-doc-types-page.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';

import type { DocumentationRole } from '../interfaces/documentation-role';
import type { AdminDocType } from '../models/document-admin.models';
import type { AdminWorkflowDefinition } from '../models/document-admin.models';
import { AdminModalComponent } from '../components/admin-modal/admin-modal.component';
import { AdminShellComponent } from '../components/admin-shell/admin-shell.component';
import { AdminToggleComponent } from '../components/admin-toggle/admin-toggle.component';
import { DocIconComponent } from '../components/doc-icon/doc-icon.component';
import { DocumentAdminService } from '../services/document-admin.service';
import { DocumentationNavigationService } from '../services/documentation-navigation.service';
import { DocumentationNotificationService } from '../../core/services/documentation-notification.service';
import { formatDocumentationUxMessage } from '../../shared/utils/documentation-ux-messages';

type DocTypeForm = Omit<AdminDocType, 'id'>;

function maskBoolean(value: boolean): string {
  return value ? 'Obligatoire' : 'Optionnel';
}

@Component({
  standalone: true,
  selector: 'app-admin-doc-types-page',
  imports: [
    CommonModule,
    FormsModule,
    AdminShellComponent,
    AdminModalComponent,
    AdminToggleComponent,
    DocIconComponent,
  ],
  templateUrl: './admin-doc-types-page.component.html',
})
export class AdminDocTypesPageComponent implements OnInit {
  readonly role$ = this.nav.role$;
  readonly maskBoolean = maskBoolean;

  loading = true;
  docTypes: AdminDocType[] = [];
  workflows: AdminWorkflowDefinition[] = [];

  modalOpen = false;
  modalMode: 'create' | 'edit' = 'create';
  editingId: string | null = null;
  form: DocTypeForm = {
    name: '',
    code: '',
    description: '',
    department: '',
    retentionDays: 0,
    workflowId: '',
    mandatory: false,
  };
  formErrors: Record<string, string> = {};
  saving = false;
  successMessage: string | null = null;
  deletingId: string | null = null;

  constructor(
    private readonly nav: DocumentationNavigationService,
    private readonly admin: DocumentAdminService,
    private readonly notify: DocumentationNotificationService,
  ) {}

  ngOnInit(): void {
    void this.bootstrap();
  }

  private async bootstrap(): Promise<void> {
    await this.reload();
    this.loading = false;
  }

  workflowLabel(id: string): string {
    return this.workflows.find((w) => w.id === id)?.name ?? id;
  }

  async reload(): Promise<void> {
    const [types, defs] = await Promise.all([this.admin.getDocTypes(), this.admin.getWorkflowDefinitions()]);
    this.docTypes = types;
    this.workflows = defs;
  }

  isAdmin(role: DocumentationRole): boolean {
    return role === 'Admin';
  }

  openCreate(): void {
    this.modalMode = 'create';
    this.editingId = null;
    this.form = {
      name: '',
      code: '',
      description: '',
      department: '',
      retentionDays: 0,
      workflowId: this.workflows[0]?.id ?? '',
      mandatory: false,
    };
    this.formErrors = {};
    this.successMessage = null;
    this.modalOpen = true;
  }

  openEdit(type: AdminDocType): void {
    this.modalMode = 'edit';
    this.editingId = type.id;
    this.form = {
      name: type.name,
      code: type.code,
      description: type.description,
      department: type.department,
      retentionDays: type.retentionDays,
      workflowId: type.workflowId,
      mandatory: type.mandatory,
    };
    this.formErrors = {};
    this.modalOpen = true;
  }

  closeModal(): void {
    this.modalOpen = false;
  }

  validateForm(): Record<string, string> {
    const e: Record<string, string> = {};
    if (!this.form.name.trim()) e['name'] = 'Nom requis.';
    if (!this.form.code.trim()) e['code'] = 'Code requis.';
    if (!this.form.department.trim()) e['department'] = 'Département requis.';
    if (!this.form.workflowId.trim()) e['workflowId'] = 'Workflow requis.';
    if (Number.isNaN(this.form.retentionDays) || this.form.retentionDays < 0) e['retentionDays'] = 'Durée invalide.';
    return e;
  }

  async onSubmit(): Promise<void> {
    this.successMessage = null;
    const e = this.validateForm();
    this.formErrors = e;
    if (Object.keys(e).length > 0) return;

    const wasCreate = this.modalMode === 'create';
    this.saving = true;
    try {
      if (this.modalMode === 'create') {
        await this.admin.createDocType(this.form);
      } else if (this.editingId) {
        await this.admin.updateDocType(this.editingId, this.form);
      }
      await this.reload();
      this.modalOpen = false;
      this.successMessage = wasCreate ? 'Type de document ajouté.' : 'Type de document mis à jour.';
      this.notify.showSuccess(
        wasCreate ? 'Le type de document a ete ajoute.' : 'Le type de document a ete mis a jour.',
      );
    } finally {
      this.saving = false;
    }
  }

  async onDelete(id: string): Promise<void> {
    const ok = window.confirm('Supprimer ce type de document ? Cette action est irreversible.');
    if (!ok) return;
    this.deletingId = id;
    try {
      await this.admin.deleteDocType(id);
      await this.reload();
      this.successMessage = 'Type de document supprimé.';
      this.notify.showSuccess('Le type de document a ete supprime.');
    } catch (error) {
      this.notify.showError(
        formatDocumentationUxMessage(
          error,
          'La suppression n’a pas pu etre finalisee pour le moment. Merci de reessayer.',
        ),
      );
    } finally {
      this.deletingId = null;
    }
  }

  patchForm(partial: Partial<DocTypeForm>): void {
    this.form = { ...this.form, ...partial };
  }

  onCodeInput(v: string): void {
    this.form = { ...this.form, code: v.toUpperCase() };
  }
}

@if (role$ | async; as role) {
  @if (!isAdmin(role)) {
    <app-admin-shell title="Document Types" description="Accès refusé pour ce rôle." iconName="layers">
      <div class="card-navy p-6">
        <p class="text-slate-300">Seul le rôle `Admin` peut gérer les types de documents.</p>
      </div>
    </app-admin-shell>
  } @else if (loading) {
    <app-admin-shell title="Document Types" description="Chargement des types…" iconName="layers">
      <div class="card-navy p-6">
        <p class="text-slate-300">Veuillez patienter.</p>
      </div>
    </app-admin-shell>
  } @else {
    <app-admin-shell
      title="Gestion des types de documents"
      description="CRUD complet, association au workflow et règles d’obligation"
      iconName="layers"
    >
      <div class="card-navy p-6 space-y-6">
        @if (successMessage) {
          <div class="px-4 py-3 rounded-lg bg-blue-500/10 text-blue-200 border border-blue-500/20">
            {{ successMessage }}
          </div>
        }

        <div class="flex flex-col justify-between gap-3 md:flex-row md:items-center">
          <div>
            <h4 class="text-white font-bold text-lg">Types configurés</h4>
            <p class="text-sm text-slate-500 mt-1">Définissez vos catégories et leurs politiques de conservation.</p>
          </div>
          <button
            type="button"
            (click)="openCreate()"
            class="inline-flex items-center gap-2 whitespace-nowrap rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white transition-all hover:bg-blue-500 shadow-lg shadow-blue-600/20"
          >
            <app-doc-icon name="plus-circle" klass="w-4 h-4"></app-doc-icon>
            Ajouter un type
          </button>
        </div>

        <div class="card-navy p-0 overflow-hidden border border-navy-800">
          <table class="w-full text-left border-collapse">
            <thead>
              <tr class="bg-navy-800/40 border-b border-navy-800">
                <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Nom</th>
                <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Code</th>
                <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Département</th>
                <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Durée (jours)</th>
                <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Workflow</th>
                <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Obligatoire</th>
                <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider text-right">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-navy-800">
              @for (dt of docTypes; track dt.id) {
                <tr class="hover:bg-navy-800/20 transition-colors">
                  <td class="px-6 py-4">
                    <div class="text-sm font-semibold text-slate-200">{{ dt.name }}</div>
                    @if (dt.description) {
                      <div class="text-xs text-slate-500 mt-1">{{ dt.description }}</div>
                    }
                  </td>
                  <td class="px-6 py-4 text-sm text-slate-300 font-mono">{{ dt.code }}</td>
                  <td class="px-6 py-4 text-sm text-slate-300">{{ dt.department }}</td>
                  <td class="px-6 py-4 text-sm text-slate-300">{{ dt.retentionDays }}</td>
                  <td class="px-6 py-4 text-sm text-slate-300">{{ workflowLabel(dt.workflowId) }}</td>
                  <td class="px-6 py-4">
                    <span
                      class="px-2.5 py-0.5 rounded-full text-[11px] font-semibold border"
                      [ngClass]="
                        dt.mandatory
                          ? 'bg-blue-500/10 text-blue-300 border-blue-500/20'
                          : 'bg-slate-500/10 text-slate-300 border-slate-500/20'
                      "
                    >
                      {{ maskBoolean(dt.mandatory) }}
                    </span>
                  </td>
                  <td class="px-6 py-4 text-right">
                    <div class="flex items-center justify-end gap-2">
                      <button
                        type="button"
                        (click)="openEdit(dt)"
                        class="inline-flex items-center justify-center rounded-lg border border-navy-700 px-3 py-2 text-slate-300 transition-colors hover:bg-navy-800 hover:text-white"
                        title="Modifier ce type de document"
                      >
                        <app-doc-icon name="edit" klass="w-4 h-4"></app-doc-icon>
                      </button>
                      <button
                        type="button"
                        (click)="onDelete(dt.id)"
                        class="inline-flex items-center justify-center rounded-lg border border-red-500/20 px-3 py-2 text-red-400 transition-colors hover:bg-red-500/10"
                        title="Supprimer ce type de document"
                        [disabled]="deletingId === dt.id"
                      >
                        @if (deletingId === dt.id) {
                          <span class="h-4 w-4 animate-spin rounded-full border-2 border-current border-r-transparent" aria-hidden="true"></span>
                        } @else {
                          <app-doc-icon name="trash-2" klass="w-4 h-4"></app-doc-icon>
                        }
                      </button>
                    </div>
                  </td>
                </tr>
              }
              @if (docTypes.length === 0) {
                <tr>
                  <td colspan="7" class="px-6 py-10 text-center text-slate-500">Aucun type de document configuré.</td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      </div>

      <app-admin-modal
        [open]="modalOpen"
        [title]="modalMode === 'create' ? 'Ajouter un type de document' : 'Modifier le type de document'"
        description="CRUD complet avec association au workflow et règle d’obligation."
        (close)="closeModal()"
      >
        <div modalBody class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label class="text-sm font-semibold text-white">Nom</label>
            <input
              [(ngModel)]="form.name"
              class="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
            />
            @if (formErrors['name']) {
              <p class="text-xs text-red-400 mt-1">{{ formErrors['name'] }}</p>
            }
          </div>
          <div>
            <label class="text-sm font-semibold text-white">Code</label>
            <input
              [ngModel]="form.code"
              (ngModelChange)="onCodeInput($event)"
              class="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
            />
            @if (formErrors['code']) {
              <p class="text-xs text-red-400 mt-1">{{ formErrors['code'] }}</p>
            }
          </div>
          <div class="md:col-span-2">
            <label class="text-sm font-semibold text-white">Description</label>
            <textarea
              [(ngModel)]="form.description"
              rows="3"
              class="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500 resize-none"
            ></textarea>
          </div>
          <div>
            <label class="text-sm font-semibold text-white">Département</label>
            <input
              [(ngModel)]="form.department"
              class="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
            />
            @if (formErrors['department']) {
              <p class="text-xs text-red-400 mt-1">{{ formErrors['department'] }}</p>
            }
          </div>
          <div>
            <label class="text-sm font-semibold text-white">Durée de conservation (jours)</label>
            <input
              type="number"
              min="0"
              [(ngModel)]="form.retentionDays"
              class="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
            />
            @if (formErrors['retentionDays']) {
              <p class="text-xs text-red-400 mt-1">{{ formErrors['retentionDays'] }}</p>
            }
          </div>
          <div>
            <label class="text-sm font-semibold text-white">Workflow associé</label>
            <select
              [(ngModel)]="form.workflowId"
              class="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
            >
              @for (w of workflows; track w.id) {
                <option [value]="w.id">{{ w.name }}</option>
              }
            </select>
            @if (formErrors['workflowId']) {
              <p class="text-xs text-red-400 mt-1">{{ formErrors['workflowId'] }}</p>
            }
          </div>
          <div class="md:col-span-1">
            <div class="mt-8">
              <app-admin-toggle
                [checked]="form.mandatory"
                (checkedChange)="patchForm({ mandatory: $event })"
                label="Obligatoire"
              ></app-admin-toggle>
            </div>
          </div>
        </div>
        <div modalFooter class="flex flex-col sm:flex-row justify-end gap-3">
          <button
            type="button"
            (click)="closeModal()"
            class="whitespace-nowrap rounded-lg border border-navy-800 px-6 py-3 font-bold text-slate-200 transition-all hover:bg-navy-800/50"
            [disabled]="saving"
          >
            Annuler
          </button>
          <button
            type="button"
            (click)="onSubmit()"
            class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg px-6 py-3 font-bold text-white transition-all"
            [ngClass]="
              saving ? 'bg-slate-600 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-500 shadow-lg shadow-blue-600/20'
            "
            [disabled]="saving"
          >
            @if (saving) {
              <span class="h-4 w-4 animate-spin rounded-full border-2 border-current border-r-transparent" aria-hidden="true"></span>
              <span>Sauvegarde...</span>
            } @else {
              <span>Sauvegarder</span>
            }
          </button>
        </div>
      </app-admin-modal>
    </app-admin-shell>
  }
}

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/admin/AdminDocTypesPage.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { Role } from '../../types';
import { ICONS } from '../../types';
import {
  AdminDocType,
  AdminWorkflowDefinition,
} from '../../adminDocumentation/documentAdminModels';
import {
  createDocType,
  deleteDocType,
  getDocTypes,
  getWorkflowDefinitions,
  updateDocType,
} from '../../adminDocumentation/documentAdminService';
import { AdminShell } from './AdminShell';
import { AdminModal } from './AdminModal';
import { AdminToggle } from './AdminToggle';

type DocTypeForm = Omit<AdminDocType, 'id'>;

function maskBoolean(value: boolean) {
  return value ? 'Obligatoire' : 'Optionnel';
}

export const AdminDocTypesPage: React.FC<{ role: Role }> = ({ role }) => {
  const isAdmin = role === 'Admin';

  const [loading, setLoading] = useState(true);
  const [docTypes, setDocTypes] = useState<AdminDocType[]>([]);
  const [workflows, setWorkflows] = useState<AdminWorkflowDefinition[]>([]);

  const [modalOpen, setModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState<'create' | 'edit'>('create');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<DocTypeForm>({
    name: '',
    code: '',
    description: '',
    department: '',
    retentionDays: 0,
    workflowId: '',
    mandatory: false,
  });
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  const workflowLabelById = useMemo(() => {
    const map = new Map<string, string>();
    workflows.forEach((w) => map.set(w.id, w.name));
    return map;
  }, [workflows]);

  const reload = async () => {
    const [types, defs] = await Promise.all([getDocTypes(), getWorkflowDefinitions()]);
    setDocTypes(types);
    setWorkflows(defs);
  };

  useEffect(() => {
    let mounted = true;
    (async () => {
      await reload();
      if (!mounted) return;
      setLoading(false);
    })();
    return () => {
      mounted = false;
    };
  }, []);

  const openCreate = () => {
    setModalMode('create');
    setEditingId(null);
    setForm({
      name: '',
      code: '',
      description: '',
      department: '',
      retentionDays: 0,
      workflowId: workflows[0]?.id ?? '',
      mandatory: false,
    });
    setFormErrors({});
    setSuccessMessage(null);
    setModalOpen(true);
  };

  const openEdit = (type: AdminDocType) => {
    setModalMode('edit');
    setEditingId(type.id);
    setForm({
      name: type.name,
      code: type.code,
      description: type.description,
      department: type.department,
      retentionDays: type.retentionDays,
      workflowId: type.workflowId,
      mandatory: type.mandatory,
    });
    setFormErrors({});
    setModalOpen(true);
  };

  const validateForm = (): Record<string, string> => {
    const e: Record<string, string> = {};
    if (!form.name.trim()) e.name = 'Nom requis.';
    if (!form.code.trim()) e.code = 'Code requis.';
    if (!form.department.trim()) e.department = 'Département requis.';
    if (!form.workflowId.trim()) e.workflowId = 'Workflow requis.';
    if (Number.isNaN(form.retentionDays) || form.retentionDays < 0) e.retentionDays = 'Durée invalide.';
    return e;
  };

  const onSubmit = async () => {
    setSuccessMessage(null);
    const e = validateForm();
    setFormErrors(e);
    if (Object.keys(e).length > 0) return;

    setSaving(true);
    try {
      if (modalMode === 'create') {
        await createDocType(form);
      } else if (editingId) {
        await updateDocType(editingId, form);
      }
      await reload();
      setModalOpen(false);
    } finally {
      setSaving(false);
    }
    setSuccessMessage(modalMode === 'create' ? 'Type de document ajouté.' : 'Type de document mis à jour.');
  };

  const onDelete = async (id: string) => {
    const ok = window.confirm('Supprimer ce type de document ? Cette action est irréversible (mock).');
    if (!ok) return;
    await deleteDocType(id);
    await reload();
    setSuccessMessage('Type de document supprimé.');
  };

  if (!isAdmin) {
    return (
      <AdminShell title="Document Types" description="Accès refusé pour ce rôle." icon={ICONS.Types}>
        <div className="card-navy p-6">
          <p className="text-slate-300">Seul le rôle `Admin` peut gérer les types de documents.</p>
        </div>
      </AdminShell>
    );
  }

  if (loading) {
    return (
      <AdminShell title="Document Types" description="Chargement des types…" icon={ICONS.Types}>
        <div className="card-navy p-6">
          <p className="text-slate-300">Veuillez patienter.</p>
        </div>
      </AdminShell>
    );
  }

  return (
    <AdminShell title="Gestion des types de documents" description="CRUD complet, association au workflow et règles d’obligation" icon={ICONS.Types}>
      <div className="card-navy p-6 space-y-6">
        {successMessage && (
          <div className="px-4 py-3 rounded-lg bg-blue-500/10 text-blue-200 border border-blue-500/20">
            {successMessage}
          </div>
        )}

        <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
          <div>
            <h4 className="text-white font-bold text-lg">Types configurés</h4>
            <p className="text-sm text-slate-500 mt-1">Définissez vos catégories et leurs politiques de conservation.</p>
          </div>
          <button
            onClick={openCreate}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 rounded-lg text-sm font-semibold text-white hover:bg-blue-500 transition-all shadow-lg shadow-blue-600/20"
          >
            <ICONS.PlusCircle className="w-4 h-4" />
            Ajouter un type
          </button>
        </div>

        <div className="card-navy p-0 overflow-hidden border border-navy-800">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-navy-800/40 border-b border-navy-800">
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Nom</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Code</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Département</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Durée (jours)</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Workflow</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Obligatoire</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-navy-800">
              {docTypes.map((dt) => (
                <tr key={dt.id} className="hover:bg-navy-800/20 transition-colors">
                  <td className="px-6 py-4">
                    <div className="text-sm font-semibold text-slate-200">{dt.name}</div>
                    {dt.description && <div className="text-xs text-slate-500 mt-1">{dt.description}</div>}
                  </td>
                  <td className="px-6 py-4 text-sm text-slate-300 font-mono">{dt.code}</td>
                  <td className="px-6 py-4 text-sm text-slate-300">{dt.department}</td>
                  <td className="px-6 py-4 text-sm text-slate-300">{dt.retentionDays}</td>
                  <td className="px-6 py-4 text-sm text-slate-300">{workflowLabelById.get(dt.workflowId) ?? dt.workflowId}</td>
                  <td className="px-6 py-4">
                    <span className={`px-2.5 py-0.5 rounded-full text-[11px] font-semibold border ${dt.mandatory ? 'bg-blue-500/10 text-blue-300 border-blue-500/20' : 'bg-slate-500/10 text-slate-300 border-slate-500/20'}`}>
                      {maskBoolean(dt.mandatory)}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <button
                        onClick={() => openEdit(dt)}
                        className="p-2 text-slate-400 hover:text-white hover:bg-navy-800 rounded-lg transition-colors"
                        title="Modifier"
                      >
                        <ICONS.Edit className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => onDelete(dt.id)}
                        className="p-2 text-red-500 hover:text-red-400 hover:bg-red-500/10 rounded-lg transition-colors"
                        title="Supprimer"
                      >
                        <ICONS.Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
              {docTypes.length === 0 && (
                <tr>
                  <td colSpan={7} className="px-6 py-10 text-center text-slate-500">
                    Aucun type de document configuré.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      <AdminModal
        open={modalOpen}
        title={modalMode === 'create' ? 'Ajouter un type de document' : 'Modifier le type de document'}
        description="CRUD complet avec association au workflow et règle d’obligation."
        onClose={() => setModalOpen(false)}
        footer={
          <div className="flex flex-col sm:flex-row justify-end gap-3">
            <button
              onClick={() => setModalOpen(false)}
              className="px-6 py-3 rounded-lg font-bold text-slate-200 border border-navy-800 hover:bg-navy-800/50 transition-all"
              disabled={saving}
              type="button"
            >
              Annuler
            </button>
            <button
              onClick={onSubmit}
              className={`px-6 py-3 rounded-lg font-bold text-white transition-all ${
                saving ? 'bg-slate-600 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-500 shadow-lg shadow-blue-600/20'
              }`}
              disabled={saving}
              type="button"
            >
              {saving ? 'Sauvegarde…' : 'Sauvegarder'}
            </button>
          </div>
        }
      >
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="text-sm font-semibold text-white">Nom</label>
            <input
              value={form.name}
              onChange={(e) => setForm({ ...form, name: e.target.value })}
              className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
            />
            {formErrors.name && <p className="text-xs text-red-400 mt-1">{formErrors.name}</p>}
          </div>
          <div>
            <label className="text-sm font-semibold text-white">Code</label>
            <input
              value={form.code}
              onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })}
              className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
            />
            {formErrors.code && <p className="text-xs text-red-400 mt-1">{formErrors.code}</p>}
          </div>
          <div className="md:col-span-2">
            <label className="text-sm font-semibold text-white">Description</label>
            <textarea
              value={form.description}
              onChange={(e) => setForm({ ...form, description: e.target.value })}
              rows={3}
              className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500 resize-none"
            />
          </div>
          <div>
            <label className="text-sm font-semibold text-white">Département</label>
            <input
              value={form.department}
              onChange={(e) => setForm({ ...form, department: e.target.value })}
              className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
            />
            {formErrors.department && <p className="text-xs text-red-400 mt-1">{formErrors.department}</p>}
          </div>
          <div>
            <label className="text-sm font-semibold text-white">Durée de conservation (jours)</label>
            <input
              type="number"
              min={0}
              value={form.retentionDays}
              onChange={(e) => setForm({ ...form, retentionDays: Number(e.target.value) })}
              className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
            />
            {formErrors.retentionDays && <p className="text-xs text-red-400 mt-1">{formErrors.retentionDays}</p>}
          </div>
          <div>
            <label className="text-sm font-semibold text-white">Workflow associé</label>
            <select
              value={form.workflowId}
              onChange={(e) => setForm({ ...form, workflowId: e.target.value })}
              className="mt-2 w-full bg-navy-800 border border-navy-700 rounded-lg p-3 text-sm text-slate-200 outline-none focus:border-blue-500"
            >
              {workflows.map((w) => (
                <option key={w.id} value={w.id}>
                  {w.name}
                </option>
              ))}
            </select>
            {formErrors.workflowId && <p className="text-xs text-red-400 mt-1">{formErrors.workflowId}</p>}
          </div>
          <div className="md:col-span-1">
            <div className="mt-8">
              <AdminToggle
                checked={form.mandatory}
                onChange={(next) => setForm({ ...form, mandatory: next })}
                label="Obligatoire"
              />
            </div>
          </div>
        </div>
      </AdminModal>
    </AdminShell>
  );
};
