// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/components/admin-modal/admin-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  standalone: true,
  selector: 'app-admin-modal',
  templateUrl: './admin-modal.component.html',
})
export class AdminModalComponent {
  @Input({ required: true }) open = false;
  @Input({ required: true }) title = '';
  @Input() description?: string;
  @Output() close = new EventEmitter<void>();

  closeModal(): void {
    this.close.emit();
  }
}

@if (open) {
  <div class="fixed inset-0 z-[100] flex items-center justify-center p-4">
    <div class="absolute inset-0 bg-navy-950/60 backdrop-blur-sm" (click)="closeModal()" role="presentation"></div>
    <div class="relative w-full max-w-3xl card-navy p-6">
      <div class="flex items-start justify-between gap-4 mb-4">
        <div>
          <h3 class="text-lg font-bold text-white">{{ title }}</h3>
          @if (description) {
            <p class="text-sm text-slate-500 mt-1">{{ description }}</p>
          }
        </div>
        <button
          type="button"
          (click)="closeModal()"
          class="p-2 text-slate-400 hover:text-white hover:bg-navy-800 rounded-lg transition-colors"
          aria-label="Fermer"
        >
          X
        </button>
      </div>
      <div class="space-y-4">
        <ng-content select="[modalBody]"></ng-content>
      </div>
      <div class="mt-6">
        <ng-content select="[modalFooter]"></ng-content>
      </div>
    </div>
  </div>
}

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/admin/AdminModal.tsx
import React from 'react';

export function AdminModal(props: {
  open: boolean;
  title: string;
  description?: string;
  onClose: () => void;
  children: React.ReactNode;
  footer?: React.ReactNode;
}) {
  const { open, title, description, onClose, children, footer } = props;

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-navy-950/60 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-3xl card-navy p-6">
        <div className="flex items-start justify-between gap-4 mb-4">
          <div>
            <h3 className="text-lg font-bold text-white">{title}</h3>
            {description && <p className="text-sm text-slate-500 mt-1">{description}</p>}
          </div>
          <button
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-white hover:bg-navy-800 rounded-lg transition-colors"
            aria-label="Fermer"
          >
            X
          </button>
        </div>
        <div className="space-y-4">{children}</div>
        {footer && <div className="mt-6">{footer}</div>}
      </div>
    </div>
  );
}
