// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/components/admin-shell/admin-shell.component.ts
import { Component, Input } from '@angular/core';

import { DocIconComponent } from '../doc-icon/doc-icon.component';

@Component({
  standalone: true,
  selector: 'app-admin-shell',
  imports: [DocIconComponent],
  templateUrl: './admin-shell.component.html',
})
export class AdminShellComponent {
  @Input({ required: true }) title = '';
  @Input({ required: true }) description = '';
  @Input() iconName = 'settings';
}

<div class="space-y-6">
  <div class="flex items-center gap-4">
    <div class="w-12 h-12 bg-blue-600/10 rounded-xl flex items-center justify-center text-blue-500">
      <app-doc-icon [name]="iconName" klass="w-6 h-6"></app-doc-icon>
    </div>
    <div>
      <h3 class="text-xl font-bold text-white">{{ title }}</h3>
      <p class="text-sm text-slate-500">{{ description }}</p>
    </div>
  </div>
  <ng-content></ng-content>
</div>

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/admin/AdminShell.tsx
import React from 'react';
import { ICONS } from '../../types';

type AdminShellIcon = any;

export function AdminShell(props: {
  title: string;
  description: string;
  icon?: AdminShellIcon;
  children: React.ReactNode;
}) {
  const { title, description, icon, children } = props;
  const Icon = icon ?? ICONS.Config;

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <div className="w-12 h-12 bg-blue-600/10 rounded-xl flex items-center justify-center text-blue-500">
          <Icon className="w-6 h-6" />
        </div>
        <div>
          <h3 className="text-xl font-bold text-white">{title}</h3>
          <p className="text-sm text-slate-500">{description}</p>
        </div>
      </div>
      {children}
    </div>
  );
}
