// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/pages/admin-workflow-page.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

import type { DocumentationRole } from '../interfaces/documentation-role';
import { AdminShellComponent } from '../components/admin-shell/admin-shell.component';
import { DocumentationNavigationService } from '../services/documentation-navigation.service';

@Component({
  standalone: true,
  selector: 'app-admin-workflow-page',
  imports: [CommonModule, AdminShellComponent],
  templateUrl: './admin-workflow-page.component.html',
})
export class AdminWorkflowPageComponent {
  readonly role$ = this.nav.role$;

  constructor(private readonly nav: DocumentationNavigationService) {}

  isAdmin(role: DocumentationRole): boolean {
    return role === 'Admin';
  }
}

@if (role$ | async; as role) {
  <app-admin-shell
    title="Configuration du workflow"
    description="Workflow fixe (pas de configuration par Admin)"
    iconName="git-branch"
  >
    <div class="card-navy p-6 space-y-2">
      <p class="text-slate-200">
        Seul le rôle <span class="font-bold">RH</span> peut approuver ou rejeter une demande de document.
      </p>
      <p class="text-slate-400 text-sm">
        Les rôles <span class="font-semibold">Coach</span>, <span class="font-semibold">Manager</span> et
        <span class="font-semibold">RP</span>
        ne peuvent pas utiliser les actions <span class="font-semibold">Approve</span> /
        <span class="font-semibold">Reject</span>.
      </p>
      @if (isAdmin(role)) {
        <p class="text-amber-400 text-sm">
          La configuration du flux n’est pas nécessaire côté <span class="font-semibold">Admin</span>.
        </p>
      }
    </div>
  </app-admin-shell>
}

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/admin/AdminWorkflowPage.tsx
import React from 'react';
import { Role, ICONS } from '../../types';
import { AdminShell } from './AdminShell';

export const AdminWorkflowPage: React.FC<{ role: Role }> = ({ role }) => {
  return (
    <AdminShell
      title="Configuration du workflow"
      description="Workflow fixe (pas de configuration par Admin)"
      icon={ICONS.Workflow}
    >
      <div className="card-navy p-6 space-y-2">
        <p className="text-slate-200">
          Seul le rôle <span className="font-bold">RH</span> peut approuver ou rejeter une demande de document.
        </p>
        <p className="text-slate-400 text-sm">
          Les rôles <span className="font-semibold">Coach</span>, <span className="font-semibold">Manager</span> et <span className="font-semibold">RP</span>{" "}
          ne peuvent pas utiliser les actions <span className="font-semibold">Approve</span> / <span className="font-semibold">Reject</span>.
        </p>
        {role === 'Admin' && (
          <p className="text-amber-400 text-sm">
            La configuration du flux n’est pas nécessaire côté <span className="font-semibold">Admin</span>.
          </p>
        )}
      </div>
    </AdminShell>
  );
};
