// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/components/admin-toggle/admin-toggle.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  standalone: true,
  selector: 'app-admin-toggle',
  templateUrl: './admin-toggle.component.html',
})
export class AdminToggleComponent {
  @Input({ required: true }) checked = false;
  @Input() label?: string;
  @Input() disabled = false;
  @Input() titleAttr?: string;
  @Output() checkedChange = new EventEmitter<boolean>();

  onChange(v: boolean): void {
    if (this.disabled) return;
    this.checkedChange.emit(v);
  }
}

<label
  class="flex items-center gap-3"
  [class.opacity-60]="disabled"
  [class.cursor-not-allowed]="disabled"
  [class.cursor-pointer]="!disabled"
  [attr.title]="titleAttr ?? null"
>
  <span class="relative inline-flex items-center">
    <input
      type="checkbox"
      class="sr-only"
      [checked]="checked"
      [disabled]="disabled"
      (change)="onChange($any($event.target).checked)"
    />
    <span class="w-11 h-6 rounded-full transition-colors" [class.bg-blue-600]="checked" [class.bg-navy-800]="!checked">
      <span
        class="absolute top-0 left-0 w-6 h-6 rounded-full bg-navy-900 border border-navy-800 transition-transform"
        [class.translate-x-5]="checked"
        [class.translate-x-0]="!checked"
      ></span>
    </span>
  </span>
  @if (label) {
    <span class="text-sm text-slate-300">{{ label }}</span>
  }
</label>

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/admin/AdminToggle.tsx
import React from 'react';

export function AdminToggle(props: {
  checked: boolean;
  onChange: (next: boolean) => void;
  label?: string;
  disabled?: boolean;
  title?: string;
}) {
  const { checked, onChange, label, disabled, title } = props;

  return (
    <label
      className={`flex items-center gap-3 ${disabled ? 'opacity-60 cursor-not-allowed' : 'cursor-pointer'}`}
      title={title}
    >
      <span className="relative inline-flex items-center">
        <input
          type="checkbox"
          className="sr-only"
          checked={checked}
          disabled={disabled}
          onChange={(e) => onChange(e.target.checked)}
        />
        <span
          className={`w-11 h-6 rounded-full transition-colors ${
            checked ? 'bg-blue-600' : 'bg-navy-800'
          }`}
        >
          <span
            className={`absolute top-0 left-0 w-6 h-6 rounded-full bg-navy-900 border border-navy-800 transition-transform ${
              checked ? 'translate-x-5' : 'translate-x-0'
            }`}
          />
        </span>
      </span>
      {label && <span className="text-sm text-slate-300">{label}</span>}
    </label>
  );
}
