// parrainage-microservice/src/parrainage/components/StatusBadge.tsx
import React from 'react';
import type { ReferralStatus } from '../models/Referral';

/** Matches Documentation Badge: px-2.5 py-0.5 rounded-full text-[11px] font-semibold border */
const STATUS_STYLES: Record<ReferralStatus, string> = {
  SUBMITTED: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
  APPROVED: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
  REJECTED: 'bg-red-500/10 text-red-500 border-red-500/20',
  REWARDED: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
};

const STATUS_LABELS: Record<ReferralStatus, string> = {
  SUBMITTED: 'En attente',
  APPROVED: 'Validé',
  REJECTED: 'Rejeté',
  REWARDED: 'Prime versée',
};

export const StatusBadge: React.FC<{ status: ReferralStatus }> = ({ status }) => (
  <span
    className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-[11px] font-semibold ${STATUS_STYLES[status]}`}
  >
    {STATUS_LABELS[status]}
  </span>
);

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/components/status-badge/status-badge.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-status-badge',
  standalone: true,
  imports: [CommonModule],
  template: `
    <span
      class="inline-flex items-center whitespace-nowrap px-2.5 py-0.5 rounded-full text-[11px] font-semibold border"
      [ngClass]="styles[status] || fallback"
    >
      {{ statusLabels[status] || status }}
    </span>
  `,
})
export class StatusBadgeComponent {
  @Input({ required: true }) status!: string;

  readonly statusLabels: Record<string, string> = {
    Generated: 'Document généré',
    Approved: 'Approuvé',
    Pending: 'En attente',
    Rejected: 'Rejeté',
    Cancelled: 'Annulé',
  };

  readonly styles: Record<string, string> = {
    Generated: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
    Approved: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    Pending: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
    Rejected: 'bg-red-500/10 text-red-500 border-red-500/20',
    Cancelled: 'bg-slate-500/10 text-slate-400 border-slate-500/25',
  };

  readonly fallback = 'bg-slate-500/10 text-slate-500 border-slate-500/20';
}
