// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/dashboards/RPDashboard.tsx
import React from 'react';
import { motion } from 'motion/react';
import { ICONS, Role } from '../../types';
import { MOCK_REQUESTS } from '../../mockData';
import { filterByEmployeeScope } from '../../lib/documentationFilters';
import { useDocumentationHierarchyDrill } from '../../contexts/DocumentationHierarchyDrillContext';
import { DocDrillBar } from '../DocDrillBar';
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from 'recharts';

interface Props {
  setActiveTab: (tab: string) => void;
  role: Role;
}

export const RPDashboard: React.FC<Props> = ({ role }) => {
  const { drill } = useDocumentationHierarchyDrill();
  const scopedReq = filterByEmployeeScope(MOCK_REQUESTS, role, drill);
  const totalRequests = scopedReq.length;
  const approved = scopedReq.filter(
    (r) => r.status === 'Approved' || r.status === 'Generated'
  ).length;
  const rejected = scopedReq.filter((r) => r.status === 'Rejected').length;

  const approvalRate =
    totalRequests > 0 ? Math.round((approved / totalRequests) * 100) : 0;
  const rejectionRate =
    totalRequests > 0 ? Math.round((rejected / totalRequests) * 100) : 0;

  const stats = [
    {
      label: 'Total des demandes',
      value: totalRequests,
      icon: ICONS.History,
      color: 'text-blue-500',
      bg: 'bg-blue-500/10',
    },
    {
      label: 'Taux d’approbation',
      value: `${approvalRate} %`,
      icon: ICONS.Check,
      color: 'text-emerald-500',
      bg: 'bg-emerald-500/10',
    },
    {
      label: 'Taux de rejet',
      value: `${rejectionRate} %`,
      icon: ICONS.X,
      color: 'text-red-500',
      bg: 'bg-red-500/10',
    },
    {
      label: 'Utilisateurs actifs',
      value: 142,
      icon: ICONS.Team,
      color: 'text-indigo-500',
      bg: 'bg-indigo-500/10',
    },
  ];

  const evolutionData = [
    { name: 'janv.', requests: 45 },
    { name: 'févr.', requests: 52 },
    { name: 'mars', requests: 38 },
    { name: 'avr.', requests: 65 },
    { name: 'mai', requests: 48 },
    { name: 'juin', requests: 70 },
  ];

  const typeData = [
    { name: 'Attestation', value: 45 },
    { name: 'Fiche de paie', value: 30 },
    { name: 'Contrat', value: 15 },
    { name: 'Avenant', value: 10 },
  ];

  const COLORS = ['#3b82f6', '#10b981', '#6366f1', '#f59e0b'];

  return (
    <div className="space-y-8">
      <DocDrillBar role={role} />
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, i) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="card-navy p-6 flex items-center justify-between"
          >
            <div>
              <p className="text-sm text-slate-400 font-medium mb-1">{stat.label}</p>
              <h3 className="text-3xl font-bold text-white">{stat.value}</h3>
            </div>
            <div className={`w-12 h-12 ${stat.bg} rounded-xl flex items-center justify-center`}>
              <stat.icon className={`w-6 h-6 ${stat.color}`} />
            </div>
          </motion.div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="card-navy p-6">
          <h3 className="text-lg font-semibold text-white mb-6">
            Évolution des demandes
          </h3>
          <div className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={evolutionData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                <XAxis
                  dataKey="name"
                  stroke="#64748b"
                  fontSize={12}
                  tickLine={false}
                  axisLine={false}
                />
                <YAxis
                  stroke="#64748b"
                  fontSize={12}
                  tickLine={false}
                  axisLine={false}
                />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#0f172a',
                    borderColor: '#1e293b',
                    color: '#f8fafc',
                  }}
                  itemStyle={{ color: '#3b82f6' }}
                />
                <Line
                  type="monotone"
                  dataKey="requests"
                  stroke="#3b82f6"
                  strokeWidth={3}
                  dot={{ r: 4, fill: '#3b82f6', strokeWidth: 2, stroke: '#0f172a' }}
                  activeDot={{ r: 6 }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="card-navy p-6">
          <h3 className="text-lg font-semibold text-white mb-6">
            Répartition par type de document
          </h3>
          <div className="h-[300px] w-full flex items-center justify-center">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={typeData}
                  cx="50%"
                  cy="50%"
                  innerRadius={80}
                  outerRadius={110}
                  paddingAngle={5}
                  dataKey="value"
                >
                  {typeData.map((_, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#0f172a',
                    borderColor: '#1e293b',
                    color: '#f8fafc',
                  }}
                />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <div className="flex flex-wrap justify-center gap-4 mt-4">
            {typeData.map((entry, index) => (
              <div key={entry.name} className="flex items-center gap-2">
                <div
                  className="w-3 h-3 rounded-full"
                  style={{ backgroundColor: COLORS[index % COLORS.length] }}
                ></div>
                <span className="text-xs text-slate-400">
                  {entry.name} ({entry.value} %)
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/components/rp-dashboard/rp-dashboard.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnDestroy, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';

import { DocumentationIdentityService } from '../../../core/services/documentation-identity.service';
import type { DocumentationRole } from '../../interfaces/documentation-role';
import { switchMapOnDocumentationContext } from '../../lib/documentation-context-refresh';
import type { DocumentationRequest } from '../../interfaces/documentation-entities';
import { filterByEmployeeScope } from '../../lib/documentation-filters';
import { mapDocumentRequestDto } from '../../lib/documentation-dto-mappers';
import type { HierarchyDrillSelection } from '../../lib/documentation-org-hierarchy';
import { DocumentationApiService } from '../../services/documentation-api.service';
import { DocumentationHierarchyDrillService } from '../../services/documentation-hierarchy-drill.service';
import { DocDrillBarComponent } from '../doc-drill-bar/doc-drill-bar.component';
import { DocIconComponent } from '../doc-icon/doc-icon.component';

const MONTHS_FR = ['janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin', 'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.'];

@Component({
  selector: 'app-rp-dashboard',
  standalone: true,
  imports: [CommonModule, DocIconComponent, DocDrillBarComponent],
  templateUrl: './rp-dashboard.component.html',
})
export class RpDashboardComponent implements OnInit, OnDestroy {
  @Input({ required: true }) role!: DocumentationRole;

  drill: HierarchyDrillSelection = {};
  private sub = new Subscription();

  loading = true;
  error: string | null = null;
  private allRequests: DocumentationRequest[] = [];

  evolutionData: Array<{ name: string; requests: number }> = [];
  typeData: Array<{ name: string; value: number }> = [];

  readonly COLORS = ['#3b82f6', '#10b981', '#6366f1', '#f59e0b'];

  constructor(
    private readonly hierarchy: DocumentationHierarchyDrillService,
    private readonly api: DocumentationApiService,
    private readonly identity: DocumentationIdentityService,
  ) {}

  ngOnInit(): void {
    this.sub.add(
      this.hierarchy.drill$.subscribe((d) => {
        this.drill = d;
        this.recomputeCharts();
      }),
    );
    this.sub.add(
      switchMapOnDocumentationContext(this.identity, () => this.api.getAllDocumentRequests()).subscribe({
        next: (rows) => {
          this.allRequests = rows.map(mapDocumentRequestDto);
          this.recomputeCharts();
          this.loading = false;
          this.error = null;
        },
        error: () => {
          this.allRequests = [];
          this.evolutionData = [];
          this.typeData = [];
          this.loading = false;
          this.error = 'Impossible de charger les demandes.';
        },
      }),
    );
  }

  private recomputeCharts(): void {
    const scoped = this.scopedReq;
    const now = new Date();
    const byMonth = new Map<string, number>();
    for (let i = 5; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
      const key = `${d.getFullYear()}-${d.getMonth()}`;
      byMonth.set(key, 0);
    }
    for (const r of scoped) {
      const d = new Date(r.requestDate);
      if (Number.isNaN(d.getTime())) continue;
      const key = `${d.getFullYear()}-${d.getMonth()}`;
      if (byMonth.has(key)) byMonth.set(key, (byMonth.get(key) ?? 0) + 1);
    }
    this.evolutionData = [...byMonth.entries()].map(([km, requests]) => {
      const [y, m] = km.split('-').map(Number);
      return { name: `${MONTHS_FR[m]} ${y}`, requests };
    });

    const byType = new Map<string, number>();
    for (const r of scoped) {
      byType.set(r.type, (byType.get(r.type) ?? 0) + 1);
    }
    const sorted = [...byType.entries()].sort((a, b) => b[1] - a[1]).slice(0, 6);
    this.typeData = sorted.map(([name, value]) => ({ name, value }));
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }

  get scopedReq(): DocumentationRequest[] {
    return filterByEmployeeScope(
      this.allRequests,
      this.role,
      this.identity.profile$.value,
      this.identity.directoryUsers$.value,
      this.drill,
    );
  }

  get totalRequests(): number {
    return this.scopedReq.length;
  }

  get approvalRate(): number {
    const t = this.totalRequests;
    if (t <= 0) return 0;
    const approved = this.scopedReq.filter((r) => r.status === 'Approved' || r.status === 'Generated').length;
    return Math.round((approved / t) * 100);
  }

  get rejectionRate(): number {
    const t = this.totalRequests;
    if (t <= 0) return 0;
    const rejected = this.scopedReq.filter((r) => r.status === 'Rejected').length;
    return Math.round((rejected / t) * 100);
  }

  readonly statsDef = [
    { key: 'tot', label: 'Total des demandes', icon: 'history', color: 'text-blue-500', bg: 'bg-blue-500/10' },
    { key: 'appr', label: 'Taux d’approbation', icon: 'check-circle-2', color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
    { key: 'rej', label: 'Taux de rejet', icon: 'x-circle', color: 'text-red-500', bg: 'bg-red-500/10' },
    { key: 'act', label: 'Utilisateurs actifs', icon: 'users', color: 'text-indigo-500', bg: 'bg-indigo-500/10' },
  ];

  statDisplay(key: string): string | number {
    switch (key) {
      case 'tot':
        return this.totalRequests;
      case 'appr':
        return `${this.approvalRate} %`;
      case 'rej':
        return `${this.rejectionRate} %`;
      case 'act':
        return new Set(this.scopedReq.map((r) => r.employeeId).filter(Boolean)).size;
      default:
        return 0;
    }
  }

  linePoints(): string {
    const data = this.evolutionData.length > 0 ? this.evolutionData : [{ name: '', requests: 0 }];
    const maxY = Math.max(...data.map((d) => d.requests), 1);
    const w = 400;
    const h = 220;
    const pad = 24;
    if (data.length < 2) {
      const x = pad + (w - pad * 2) / 2;
      const y = h - pad - (data[0].requests / maxY) * (h - pad * 2);
      return `${x},${y}`;
    }
    return data
      .map((d, i) => {
        const x = pad + (i / (data.length - 1)) * (w - pad * 2);
        const y = h - pad - (d.requests / maxY) * (h - pad * 2);
        return `${x},${y}`;
      })
      .join(' ');
  }

  lineDots(): Array<{ x: string; y: string }> {
    return this.linePoints()
      .split(' ')
      .filter(Boolean)
      .map((pair) => {
        const [x, y] = pair.split(',');
        return { x, y };
      });
  }

  pieSlice(index: number): string {
    const total = this.typeData.reduce((s, t) => s + t.value, 0);
    if (total <= 0) return '';
    const cx = 110;
    const cy = 110;
    const r = 110;
    const ri = 78;
    let a0 = -Math.PI / 2;
    for (let i = 0; i < index; i++) {
      a0 += (this.typeData[i].value / total) * 2 * Math.PI;
    }
    const sweep = (this.typeData[index].value / total) * 2 * Math.PI;
    const a1 = a0 + sweep;
    const x0 = cx + r * Math.cos(a0);
    const y0 = cy + r * Math.sin(a0);
    const x1 = cx + r * Math.cos(a1);
    const y1 = cy + r * Math.sin(a1);
    const xi0 = cx + ri * Math.cos(a0);
    const yi0 = cy + ri * Math.sin(a0);
    const xi1 = cx + ri * Math.cos(a1);
    const yi1 = cy + ri * Math.sin(a1);
    const large = sweep > Math.PI ? 1 : 0;
    return `M ${xi0} ${yi0} L ${x0} ${y0} A ${r} ${r} 0 ${large} 1 ${x1} ${y1} L ${xi1} ${yi1} A ${ri} ${ri} 0 ${large} 0 ${xi0} ${yi0} Z`;
  }
}

<div class="space-y-8">
  <app-doc-drill-bar [role]="role"></app-doc-drill-bar>
  @if (loading) {
    <p class="text-slate-400 text-sm">Chargement…</p>
  } @else if (error) {
    <p class="text-red-400 text-sm">{{ error }}</p>
  }
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    @for (stat of statsDef; track stat.key; let i = $index) {
      <div
        class="card-navy p-6 flex items-center justify-between doc-animate-in"
        [class.doc-stagger-0]="i === 0"
        [class.doc-stagger-1]="i === 1"
        [class.doc-stagger-2]="i === 2"
        [class.doc-stagger-3]="i === 3"
      >
        <div>
          <p class="text-sm text-slate-400 font-medium mb-1">{{ stat.label }}</p>
          <h3 class="text-3xl font-bold text-white">{{ statDisplay(stat.key) }}</h3>
        </div>
        <div class="w-12 h-12 rounded-xl flex items-center justify-center" [ngClass]="stat.bg">
          <app-doc-icon [name]="stat.icon" [klass]="'w-6 h-6 ' + stat.color"></app-doc-icon>
        </div>
      </div>
    }
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
    <div class="card-navy p-6">
      <h3 class="text-lg font-semibold text-white mb-6">Évolution des demandes</h3>
      <div class="h-[300px] w-full">
        <svg class="w-full h-full" viewBox="0 0 420 260" preserveAspectRatio="xMidYMid meet">
          <line x1="40" y1="220" x2="400" y2="220" stroke="#1e293b" stroke-width="1"></line>
          <line x1="40" y1="220" x2="40" y2="30" stroke="#1e293b" stroke-width="1"></line>
          @for (d of evolutionData; track d.name; let i = $index) {
            <text [attr.x]="50 + i * 58" y="248" fill="#64748b" font-size="11">{{ d.name }}</text>
          }
          <polyline
            fill="none"
            stroke="#3b82f6"
            stroke-width="3"
            stroke-linecap="round"
            stroke-linejoin="round"
            [attr.points]="linePoints()"
          ></polyline>
          @for (dot of lineDots(); track $index) {
            <circle
              [attr.cx]="dot.x"
              [attr.cy]="dot.y"
              r="4"
              fill="#3b82f6"
              stroke="#0f172a"
              stroke-width="2"
            ></circle>
          }
        </svg>
      </div>
    </div>

    <div class="card-navy p-6">
      <h3 class="text-lg font-semibold text-white mb-6">Répartition par type de document</h3>
      <div class="h-[300px] w-full flex flex-col items-center justify-center">
        @if (typeData.length === 0) {
          <p class="text-sm text-slate-500">Aucune demande sur la période filtrée.</p>
        } @else {
          <svg class="max-w-[280px]" viewBox="0 0 220 220">
            @for (t of typeData; track t.name; let i = $index) {
              <path [attr.d]="pieSlice(i)" [attr.fill]="COLORS[i % COLORS.length]"></path>
            }
            <circle cx="110" cy="110" r="78" fill="#0a1526"></circle>
          </svg>
          <div class="flex flex-wrap justify-center gap-4 mt-4">
            @for (entry of typeData; track entry.name; let index = $index) {
              <div class="flex items-center gap-2">
                <div class="w-3 h-3 rounded-full" [style.background-color]="COLORS[index % COLORS.length]"></div>
                <span class="text-xs text-slate-400">{{ entry.name }} ({{ entry.value }})</span>
              </div>
            }
          </div>
        }
      </div>
    </div>
  </div>
</div>
