// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/dashboards/RHDashboard.tsx
import React from 'react';
import { motion } from 'motion/react';
import { ICONS } from '../../types';
import { MOCK_REQUESTS } from '../../mockData';
import { Badge } from '../Badge';

interface Props {
  setActiveTab: (tab: string) => void;
}

export const RHDashboard: React.FC<Props> = ({ setActiveTab }) => {
  const stats = [
    {
      label: 'Total des demandes',
      value: MOCK_REQUESTS.length,
      icon: ICONS.History,
      color: 'text-blue-500',
      bg: 'bg-blue-500/10',
    },
    {
      label: 'Validations en attente',
      value: MOCK_REQUESTS.filter((r) => r.status === 'Pending').length,
      icon: ICONS.Clock,
      color: 'text-amber-500',
      bg: 'bg-amber-500/10',
    },
    {
      label: 'Générés aujourd’hui',
      value: 45,
      icon: ICONS.Check,
      color: 'text-emerald-500',
      bg: 'bg-emerald-500/10',
    },
    {
      label: 'Modèles actifs',
      value: 8,
      icon: ICONS.Edit,
      color: 'text-indigo-500',
      bg: 'bg-indigo-500/10',
    },
  ];

  return (
    <div className="space-y-8">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, i) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="card-navy p-6 flex items-center justify-between"
          >
            <div>
              <p className="text-sm text-slate-400 font-medium mb-1">{stat.label}</p>
              <h3 className="text-3xl font-bold text-white">{stat.value}</h3>
            </div>
            <div className={`w-12 h-12 ${stat.bg} rounded-xl flex items-center justify-center`}>
              <stat.icon className={`w-6 h-6 ${stat.color}`} />
            </div>
          </motion.div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-1 space-y-6">
          <h3 className="text-lg font-semibold text-white">Actions rapides</h3>
          <div className="space-y-3">
            <button
              onClick={() => setActiveTab('hr-mgmt')}
              className="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
            >
              <div className="w-10 h-10 bg-amber-600/10 rounded-lg flex items-center justify-center group-hover:bg-amber-600 transition-colors">
                <ICONS.Management className="w-5 h-5 text-amber-500 group-hover:text-white" />
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-white">Valider les demandes</p>
                <p className="text-xs text-slate-500">Documents en attente</p>
              </div>
              <ICONS.ChevronRight className="ml-auto w-4 h-4 text-slate-600" />
            </button>
            <button
              onClick={() => setActiveTab('templates')}
              className="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
            >
              <div className="w-10 h-10 bg-indigo-600/10 rounded-lg flex items-center justify-center group-hover:bg-indigo-600 transition-colors">
                <ICONS.Config className="w-5 h-5 text-indigo-500 group-hover:text-white" />
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-white">Gérer les modèles</p>
                <p className="text-xs text-slate-500">Modifier les modèles de documents</p>
              </div>
              <ICONS.ChevronRight className="ml-auto w-4 h-4 text-slate-600" />
            </button>
          </div>
        </div>

        <div className="lg:col-span-2 space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold text-white">Demandes en attente</h3>
            <button
              onClick={() => setActiveTab('hr-mgmt')}
              className="text-sm text-blue-500 hover:text-blue-400 font-medium"
            >
              Tout voir
            </button>
          </div>
          <div className="card-navy overflow-hidden">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-navy-800/50 border-b border-navy-800">
                  <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Collaborateur
                  </th>
                  <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Type
                  </th>
                  <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Date
                  </th>
                  <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    Statut
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-navy-800">
                {MOCK_REQUESTS.filter((r) => r.status === 'Pending')
                  .slice(0, 4)
                  .map((req) => (
                    <tr key={req.id} className="hover:bg-navy-800/30 transition-colors">
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-3">
                          <div className="w-8 h-8 bg-navy-800 rounded-full flex items-center justify-center">
                            <ICONS.User className="w-4 h-4 text-slate-400" />
                          </div>
                          <span className="text-sm font-medium text-slate-200">
                            {req.employeeName}
                          </span>
                        </div>
                      </td>
                      <td className="px-6 py-4 text-sm text-slate-300">{req.type}</td>
                      <td className="px-6 py-4 text-sm text-slate-400">{req.requestDate}</td>
                      <td className="px-6 py-4">
                        <Badge status={req.status} />
                      </td>
                    </tr>
                  ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/components/rh-dashboard/rh-dashboard.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { forkJoin, Subscription } from 'rxjs';

import { DocumentationIdentityService } from '../../../core/services/documentation-identity.service';
import type { DocumentationRequest } from '../../interfaces/documentation-entities';
import { switchMapOnDocumentationContext } from '../../lib/documentation-context-refresh';
import { mapDocumentRequestDto } from '../../lib/documentation-dto-mappers';
import { DocumentationApiService } from '../../services/documentation-api.service';
import { DocumentationNavigationService } from '../../services/documentation-navigation.service';
import { DocIconComponent } from '../doc-icon/doc-icon.component';
import { StatusBadgeComponent } from '../status-badge/status-badge.component';

@Component({
  selector: 'app-rh-dashboard',
  standalone: true,
  imports: [CommonModule, DocIconComponent, StatusBadgeComponent],
  templateUrl: './rh-dashboard.component.html',
})
export class RhDashboardComponent implements OnInit, OnDestroy {
  private sub = new Subscription();

  loading = true;
  error: string | null = null;
  requests: DocumentationRequest[] = [];
  stats: Array<{ label: string; value: number; icon: string; color: string; bg: string }> = [];

  constructor(
    private readonly api: DocumentationApiService,
    private readonly nav: DocumentationNavigationService,
    private readonly identity: DocumentationIdentityService,
  ) {}

  ngOnInit(): void {
    this.sub.add(
      switchMapOnDocumentationContext(this.identity, () =>
        forkJoin({
          reqs: this.api.getAllDocumentRequests(),
          types: this.api.getDocTypesForCatalog(),
        }),
      ).subscribe({
        next: ({ reqs, types }) => {
          this.requests = reqs.map(mapDocumentRequestDto);
          const pending = this.requests.filter((r) => r.status === 'Pending').length;
          const today = new Date().toISOString().slice(0, 10);
          const generatedToday = this.requests.filter(
            (r) => r.status === 'Generated' && r.requestDate.slice(0, 10) === today,
          ).length;
          this.stats = [
            {
              label: 'Total des demandes',
              value: this.requests.length,
              icon: 'history',
              color: 'text-blue-500',
              bg: 'bg-blue-500/10',
            },
            {
              label: 'Validations en attente',
              value: pending,
              icon: 'clock',
              color: 'text-amber-500',
              bg: 'bg-amber-500/10',
            },
            {
              label: 'Générés aujourd’hui',
              value: generatedToday,
              icon: 'check-circle-2',
              color: 'text-emerald-500',
              bg: 'bg-emerald-500/10',
            },
            {
              label: 'Modèles actifs',
              value: types.length,
              icon: 'file-edit',
              color: 'text-indigo-500',
              bg: 'bg-indigo-500/10',
            },
          ];
          this.loading = false;
          this.error = null;
        },
        error: () => {
          this.requests = [];
          this.stats = [];
          this.loading = false;
          this.error = 'Impossible de charger les données RH.';
        },
      }),
    );
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }

  goHrMgmt(): void {
    this.nav.navigateToTab('hr-mgmt');
  }

  goTemplates(): void {
    this.nav.navigateToTab('templates');
  }

  pendingPreview(): DocumentationRequest[] {
    return this.requests.filter((r) => r.status === 'Pending').slice(0, 4);
  }
}

<div class="space-y-8">
  @if (loading) {
    <p class="text-slate-400 text-sm">Chargement…</p>
  } @else if (error) {
    <p class="text-red-400 text-sm">{{ error }}</p>
  }

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    @for (stat of stats; track stat.label; let i = $index) {
      <div
        class="card-navy p-6 flex items-center justify-between doc-animate-in"
        [class.doc-stagger-0]="i === 0"
        [class.doc-stagger-1]="i === 1"
        [class.doc-stagger-2]="i === 2"
        [class.doc-stagger-3]="i === 3"
      >
        <div>
          <p class="text-sm text-slate-400 font-medium mb-1">{{ stat.label }}</p>
          <h3 class="text-3xl font-bold text-white">{{ stat.value }}</h3>
        </div>
        <div class="w-12 h-12 rounded-xl flex items-center justify-center" [ngClass]="stat.bg">
          <app-doc-icon [name]="stat.icon" [klass]="'w-6 h-6 ' + stat.color"></app-doc-icon>
        </div>
      </div>
    }
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
    <div class="lg:col-span-1 space-y-6">
      <h3 class="text-lg font-semibold text-white">Actions rapides</h3>
      <div class="space-y-3">
        <button
          type="button"
          (click)="goHrMgmt()"
          class="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
        >
          <div
            class="w-10 h-10 bg-amber-600/10 rounded-lg flex items-center justify-center group-hover:bg-amber-600 transition-colors"
          >
            <app-doc-icon name="settings" klass="w-5 h-5 text-amber-500 group-hover:text-white"></app-doc-icon>
          </div>
          <div class="text-left">
            <p class="text-sm font-semibold text-white">Valider les demandes</p>
            <p class="text-xs text-slate-500">Documents en attente</p>
          </div>
          <app-doc-icon name="chevron-right" klass="ml-auto w-4 h-4 text-slate-600"></app-doc-icon>
        </button>
        <button
          type="button"
          (click)="goTemplates()"
          class="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
        >
          <div
            class="w-10 h-10 bg-indigo-600/10 rounded-lg flex items-center justify-center group-hover:bg-indigo-600 transition-colors"
          >
            <app-doc-icon name="settings" klass="w-5 h-5 text-indigo-500 group-hover:text-white"></app-doc-icon>
          </div>
          <div class="text-left">
            <p class="text-sm font-semibold text-white">Gérer les modèles</p>
            <p class="text-xs text-slate-500">Modifier les modèles de documents</p>
          </div>
          <app-doc-icon name="chevron-right" klass="ml-auto w-4 h-4 text-slate-600"></app-doc-icon>
        </button>
      </div>
    </div>

    <div class="lg:col-span-2 space-y-6">
      <div class="flex items-center justify-between">
        <h3 class="text-lg font-semibold text-white">Demandes en attente</h3>
        <button type="button" (click)="goHrMgmt()" class="text-sm text-blue-500 hover:text-blue-400 font-medium">
          Tout voir
        </button>
      </div>
      <div class="card-navy overflow-hidden">
        <table class="w-full text-left border-collapse">
          <thead>
            <tr class="bg-navy-800/50 border-b border-navy-800">
              <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                Collaborateur
              </th>
              <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Type</th>
              <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Date</th>
              <th class="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase tracking-wider">Statut</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-navy-800">
            @if (!loading && !error && pendingPreview().length === 0) {
              <tr>
                <td colspan="4" class="px-6 py-8 text-center text-sm text-slate-500">
                  Aucune demande en attente.
                </td>
              </tr>
            }
            @for (req of pendingPreview(); track req.id) {
              <tr class="hover:bg-navy-800/30 transition-colors">
                <td class="px-6 py-4">
                  <div class="flex items-center gap-3">
                    <div class="w-8 h-8 bg-navy-800 rounded-full flex items-center justify-center">
                      <app-doc-icon name="user" klass="w-4 h-4 text-slate-400"></app-doc-icon>
                    </div>
                    <span class="text-sm font-medium text-slate-200">{{ req.employeeName }}</span>
                  </div>
                </td>
                <td class="px-6 py-4 text-sm text-slate-300">{{ req.type }}</td>
                <td class="px-6 py-4 text-sm text-slate-400">{{ req.requestDate }}</td>
                <td class="px-6 py-4">
                  <app-status-badge [status]="req.status"></app-status-badge>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
