// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/DocDrillBar.tsx
import React from 'react';
import type { Role } from '../types';
import { demoUserIdForRole, drillSelectOptions } from '../lib/documentationOrgHierarchy';
import { useDocumentationHierarchyDrill } from '../contexts/DocumentationHierarchyDrillContext';

/** Filtres cascade Manager → Coach → Pilotes (RP : Manager puis Coach). */
export const DocDrillBar: React.FC<{ role: Role }> = ({ role }) => {
  const { drill, setManagerId, setCoachId } = useDocumentationHierarchyDrill();
  const viewerId = demoUserIdForRole(role);
  const { managers, coaches } = drillSelectOptions(role, viewerId, drill);

  if (role === 'Manager') {
    return (
      <div className="flex flex-wrap items-center gap-2 mb-4">
        <span className="text-xs text-slate-500 uppercase tracking-wide">Périmètre</span>
        <select
          value={drill.coachId ?? ''}
          onChange={(e) => setCoachId(e.target.value || undefined)}
          className="bg-navy-900 border border-navy-700 rounded-lg py-2 px-3 text-sm text-slate-200 focus:outline-none focus:border-blue-500"
        >
          <option value="">Coach</option>
          {coaches.map((o) => (
            <option key={o.value} value={o.value}>
              {o.label}
            </option>
          ))}
        </select>
      </div>
    );
  }

  if (role === 'RP') {
    return (
      <div className="flex flex-wrap items-center gap-2 mb-4">
        <span className="text-xs text-slate-500 uppercase tracking-wide">Périmètre</span>
        <select
          value={drill.managerId ?? ''}
          onChange={(e) => setManagerId(e.target.value || undefined)}
          className="bg-navy-900 border border-navy-700 rounded-lg py-2 px-3 text-sm text-slate-200 focus:outline-none focus:border-blue-500"
        >
          <option value="">Manager</option>
          {managers.map((o) => (
            <option key={o.value} value={o.value}>
              {o.label}
            </option>
          ))}
        </select>
        <select
          value={drill.coachId ?? ''}
          onChange={(e) => setCoachId(e.target.value || undefined)}
          disabled={!drill.managerId}
          className="bg-navy-900 border border-navy-700 rounded-lg py-2 px-3 text-sm text-slate-200 focus:outline-none focus:border-blue-500 disabled:opacity-50"
        >
          <option value="">Coach</option>
          {coaches.map((o) => (
            <option key={o.value} value={o.value}>
              {o.label}
            </option>
          ))}
        </select>
      </div>
    );
  }

  return null;
};

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/components/doc-drill-bar/doc-drill-bar.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnDestroy, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';

import { DocumentationIdentityService } from '../../../core/services/documentation-identity.service';
import type { DocumentationRole } from '../../interfaces/documentation-role';
import { drillSelectOptions } from '../../lib/documentation-org-hierarchy';
import { DocumentationHierarchyDrillService } from '../../services/documentation-hierarchy-drill.service';

@Component({
  selector: 'app-doc-drill-bar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './doc-drill-bar.component.html',
})
export class DocDrillBarComponent implements OnInit, OnDestroy {
  @Input({ required: true }) role!: DocumentationRole;

  drill = this.hierarchy.drill;
  managers: { value: string; label: string }[] = [];
  coaches: { value: string; label: string }[] = [];
  pilots: { value: string; label: string }[] = [];
  private sub = new Subscription();

  constructor(
    private readonly hierarchy: DocumentationHierarchyDrillService,
    private readonly identity: DocumentationIdentityService,
  ) {}

  ngOnInit(): void {
    this.sub.add(
      this.hierarchy.drill$.subscribe((d) => {
        this.drill = d;
        this.refreshOptions();
      }),
    );
    this.sub.add(this.identity.profile$.subscribe(() => this.refreshOptions()));
    this.sub.add(this.identity.directoryUsers$.subscribe(() => this.refreshOptions()));
    this.refreshOptions();
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }

  onManagerChange(value: string): void {
    const nextManagerId = value || undefined;
    this.hierarchy.setManagerId(nextManagerId);
    this.identity.setOrgScope(nextManagerId ?? null, null);
    this.identity.bumpContextRevision();
  }

  onCoachChange(value: string): void {
    const nextCoachId = value || undefined;
    this.hierarchy.setCoachId(nextCoachId);
    if (this.role === 'Manager') {
      this.identity.setOrgScope(null, nextCoachId ?? null);
      this.identity.bumpContextRevision();
      return;
    }
    if (this.role === 'RP') {
      this.identity.setOrgScope(this.drill.managerId ?? null, nextCoachId ?? null);
      this.identity.bumpContextRevision();
    }
  }

  onPilotChange(value: string): void {
    this.hierarchy.setPilotId(value || undefined);
  }

  private refreshOptions(): void {
    const viewerId = this.identity.profile$.value?.id ?? '';
    const users = this.identity.directoryUsers$.value;
    const { managers, coaches, pilots } = drillSelectOptions(this.role, users, viewerId, this.drill);
    this.managers = managers;
    this.coaches = coaches;
    this.pilots = pilots;
  }
}

@if (role === 'Manager') {
  <div class="flex flex-wrap items-center gap-2 mb-4">
    <span class="text-xs text-slate-500 uppercase tracking-wide">Périmètre</span>
    <select
      class="bg-navy-900 border border-navy-700 rounded-lg py-2 px-3 text-sm text-slate-200 focus:outline-none focus:border-blue-500"
      [value]="drill.coachId ?? ''"
      (change)="onCoachChange($any($event.target).value)"
    >
      <option value="">Coach</option>
      @for (o of coaches; track o.value) {
        <option [value]="o.value">{{ o.label }}</option>
      }
    </select>
    <select
      class="bg-navy-900 border border-navy-700 rounded-lg py-2 px-3 text-sm text-slate-200 focus:outline-none focus:border-blue-500 disabled:opacity-50"
      [disabled]="!drill.coachId"
      [value]="drill.pilotId ?? ''"
      (change)="onPilotChange($any($event.target).value)"
    >
      <option value="">Pilote</option>
      @for (o of pilots; track o.value) {
        <option [value]="o.value">{{ o.label }}</option>
      }
    </select>
  </div>
}
@if (role === 'RP') {
  <div class="flex flex-wrap items-center gap-2 mb-4">
    <span class="text-xs text-slate-500 uppercase tracking-wide">Périmètre</span>
    <select
      class="bg-navy-900 border border-navy-700 rounded-lg py-2 px-3 text-sm text-slate-200 focus:outline-none focus:border-blue-500"
      [value]="drill.managerId ?? ''"
      (change)="onManagerChange($any($event.target).value)"
    >
      <option value="">Manager</option>
      @for (o of managers; track o.value) {
        <option [value]="o.value">{{ o.label }}</option>
      }
    </select>
    <select
      class="bg-navy-900 border border-navy-700 rounded-lg py-2 px-3 text-sm text-slate-200 focus:outline-none focus:border-blue-500 disabled:opacity-50"
      [disabled]="!drill.managerId"
      [value]="drill.coachId ?? ''"
      (change)="onCoachChange($any($event.target).value)"
    >
      <option value="">Coach</option>
      @for (o of coaches; track o.value) {
        <option [value]="o.value">{{ o.label }}</option>
      }
    </select>
    <select
      class="bg-navy-900 border border-navy-700 rounded-lg py-2 px-3 text-sm text-slate-200 focus:outline-none focus:border-blue-500 disabled:opacity-50"
      [disabled]="!drill.coachId"
      [value]="drill.pilotId ?? ''"
      (change)="onPilotChange($any($event.target).value)"
    >
      <option value="">Pilote</option>
      @for (o of pilots; track o.value) {
        <option [value]="o.value">{{ o.label }}</option>
      }
    </select>
  </div>
}
