// documentation_microservice_mykyntus/documentation_microservice_mykyntus/src/components/dashboards/AdminDashboard.tsx
import React from 'react';
import { motion } from 'motion/react';
import { ICONS } from '../../types';

interface Props {
  setActiveTab: (tab: string) => void;
}

export const AdminDashboard: React.FC<Props> = ({ setActiveTab }) => {
  const stats = [
    {
      label: 'Utilisateurs actifs',
      value: 342,
      icon: ICONS.User,
      color: 'text-blue-500',
      bg: 'bg-blue-500/10',
    },
    {
      label: 'Types de documents',
      value: 12,
      icon: ICONS.Types,
      color: 'text-amber-500',
      bg: 'bg-amber-500/10',
    },
    {
      label: 'Rôles gérés',
      value: 5,
      icon: ICONS.Permissions,
      color: 'text-emerald-500',
      bg: 'bg-emerald-500/10',
    },
    {
      label: 'Santé du système',
      value: '99,9 %',
      icon: ICONS.Activity,
      color: 'text-indigo-500',
      bg: 'bg-indigo-500/10',
    },
  ];

  return (
    <div className="space-y-8">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, i) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="card-navy p-6 flex items-center justify-between"
          >
            <div>
              <p className="text-sm text-slate-400 font-medium mb-1">{stat.label}</p>
              <h3 className="text-3xl font-bold text-white">{stat.value}</h3>
            </div>
            <div className={`w-12 h-12 ${stat.bg} rounded-xl flex items-center justify-center`}>
              <stat.icon className={`w-6 h-6 ${stat.color}`} />
            </div>
          </motion.div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-1 space-y-6">
          <h3 className="text-lg font-semibold text-white">Configuration système</h3>
          <div className="space-y-3">
            <button
              onClick={() => setActiveTab('doc-types')}
              className="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
            >
              <div className="w-10 h-10 bg-amber-600/10 rounded-lg flex items-center justify-center group-hover:bg-amber-600 transition-colors">
                <ICONS.Types className="w-5 h-5 text-amber-500 group-hover:text-white" />
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-white">Types de documents</p>
                <p className="text-xs text-slate-500">Types disponibles</p>
              </div>
              <ICONS.ChevronRight className="ml-auto w-4 h-4 text-slate-600" />
            </button>
            <button
              onClick={() => setActiveTab('permissions')}
              className="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
            >
              <div className="w-10 h-10 bg-emerald-600/10 rounded-lg flex items-center justify-center group-hover:bg-emerald-600 transition-colors">
                <ICONS.Permissions className="w-5 h-5 text-emerald-500 group-hover:text-white" />
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-white">Permissions</p>
                <p className="text-xs text-slate-500">Politiques d’accès (RBAC)</p>
              </div>
              <ICONS.ChevronRight className="ml-auto w-4 h-4 text-slate-600" />
            </button>
          </div>
        </div>

        <div className="lg:col-span-2 space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold text-white">Utilisation des modules</h3>
          </div>
          <div className="card-navy p-6 space-y-6">
            <div className="flex items-center justify-between border-b border-navy-800 pb-4">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 bg-blue-500/10 rounded-lg flex items-center justify-center">
                  <ICONS.Documents className="w-5 h-5 text-blue-500" />
                </div>
                <div>
                  <p className="text-sm font-semibold text-white">Documents générés</p>
                  <p className="text-xs text-slate-500">Total ce mois-ci</p>
                </div>
              </div>
              <span className="text-xl font-bold text-white">1 245</span>
            </div>
            <div className="flex items-center justify-between border-b border-navy-800 pb-4">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 bg-emerald-500/10 rounded-lg flex items-center justify-center">
                  <ICONS.Check className="w-5 h-5 text-emerald-500" />
                </div>
                <div>
                  <p className="text-sm font-semibold text-white">Taux de succès API</p>
                  <p className="text-xs text-slate-500">Moyenne des points de terminaison</p>
                </div>
              </div>
              <span className="text-xl font-bold text-white">99,8 %</span>
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 bg-amber-500/10 rounded-lg flex items-center justify-center">
                  <ICONS.Storage className="w-5 h-5 text-amber-500" />
                </div>
                <div>
                  <p className="text-sm font-semibold text-white">Stockage utilisé</p>
                  <p className="text-xs text-slate-500">Consommation blob</p>
                </div>
              </div>
              <span className="text-xl font-bold text-white">45,2 Go</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// documentation_microservice_mykyntus/documentation_microservice_mykyntus/frontend/src/app/documentation-react/components/admin-dashboard/admin-dashboard.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { forkJoin, Subscription } from 'rxjs';

import { DocumentationIdentityService } from '../../../core/services/documentation-identity.service';
import { switchMapOnDocumentationContext } from '../../lib/documentation-context-refresh';
import { DocumentationApiService } from '../../services/documentation-api.service';
import { DocumentationNavigationService } from '../../services/documentation-navigation.service';
import { DocIconComponent } from '../doc-icon/doc-icon.component';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [CommonModule, DocIconComponent],
  templateUrl: './admin-dashboard.component.html',
})
export class AdminDashboardComponent implements OnInit, OnDestroy {
  loading = true;
  error: string | null = null;
  stats: Array<{
    label: string;
    value: number | string;
    icon: string;
    color: string;
    bg: string;
  }> = [];

  private sub = new Subscription();

  constructor(
    private readonly nav: DocumentationNavigationService,
    private readonly api: DocumentationApiService,
    private readonly identity: DocumentationIdentityService,
  ) {}

  ngOnInit(): void {
    this.sub.add(
      switchMapOnDocumentationContext(this.identity, () =>
        forkJoin({
          requests: this.api.getAllDocumentRequests(),
          types: this.api.getDocTypesForCatalog(),
          audit: this.api.getAllAuditLogs(),
        }),
      ).subscribe({
        next: ({ requests, types, audit }) => {
          const actors = new Set(requests.map((r) => r.employeeId).filter(Boolean));
          this.stats = [
            {
              label: 'Demandes (total)',
              value: requests.length,
              icon: 'history',
              color: 'text-blue-500',
              bg: 'bg-blue-500/10',
            },
            {
              label: 'Types catalogue',
              value: types.length,
              icon: 'layers',
              color: 'text-amber-500',
              bg: 'bg-amber-500/10',
            },
            {
              label: 'Événements audit',
              value: audit.length,
              icon: 'activity',
              color: 'text-emerald-500',
              bg: 'bg-emerald-500/10',
            },
            {
              label: 'Acteurs (demandes)',
              value: actors.size,
              icon: 'user',
              color: 'text-indigo-500',
              bg: 'bg-indigo-500/10',
            },
          ];
          this.loading = false;
          this.error = null;
        },
        error: () => {
          this.stats = [];
          this.loading = false;
          this.error = 'Impossible de charger les indicateurs administrateur.';
        },
      }),
    );
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }

  go(tab: 'doc-types' | 'permissions' | 'workflow' | 'storage'): void {
    this.nav.navigateToTab(tab);
  }
}

<div class="space-y-8">
  @if (loading) {
    <p class="text-slate-400 text-sm">Chargement des indicateurs…</p>
  } @else if (error) {
    <p class="text-rose-400 text-sm">{{ error }}</p>
  }

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    @for (stat of stats; track stat.label; let i = $index) {
      <div
        class="card-navy p-6 flex items-center justify-between doc-animate-in"
        [class.doc-stagger-0]="i === 0"
        [class.doc-stagger-1]="i === 1"
        [class.doc-stagger-2]="i === 2"
        [class.doc-stagger-3]="i === 3"
      >
        <div>
          <p class="text-sm text-slate-400 font-medium mb-1">{{ stat.label }}</p>
          <h3 class="text-3xl font-bold text-white">{{ stat.value }}</h3>
        </div>
        <div class="w-12 h-12 rounded-xl flex items-center justify-center" [ngClass]="stat.bg">
          <app-doc-icon [name]="stat.icon" [klass]="'w-6 h-6 ' + stat.color"></app-doc-icon>
        </div>
      </div>
    }
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
    <div class="lg:col-span-1 space-y-6">
      <h3 class="text-lg font-semibold text-white">Configuration système</h3>
      <div class="space-y-3">
        <button
          type="button"
          (click)="go('doc-types')"
          class="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
        >
          <div
            class="w-10 h-10 bg-amber-600/10 rounded-lg flex items-center justify-center group-hover:bg-amber-600 transition-colors"
          >
            <app-doc-icon name="layers" klass="w-5 h-5 text-amber-500 group-hover:text-white"></app-doc-icon>
          </div>
          <div class="text-left">
            <p class="text-sm font-semibold text-white">Types de documents</p>
            <p class="text-xs text-slate-500">Types disponibles</p>
          </div>
          <app-doc-icon name="chevron-right" klass="ml-auto w-4 h-4 text-slate-600"></app-doc-icon>
        </button>
        <button
          type="button"
          (click)="go('permissions')"
          class="w-full card-navy p-4 flex items-center gap-4 hover:bg-navy-800 transition-all group"
        >
          <div
            class="w-10 h-10 bg-emerald-600/10 rounded-lg flex items-center justify-center group-hover:bg-emerald-600 transition-colors"
          >
            <app-doc-icon name="lock" klass="w-5 h-5 text-emerald-500 group-hover:text-white"></app-doc-icon>
          </div>
          <div class="text-left">
            <p class="text-sm font-semibold text-white">Permissions</p>
            <p class="text-xs text-slate-500">Politiques d’accès (RBAC)</p>
          </div>
          <app-doc-icon name="chevron-right" klass="ml-auto w-4 h-4 text-slate-600"></app-doc-icon>
        </button>
      </div>
    </div>

    <div class="lg:col-span-2 space-y-6">
      <div class="flex items-center justify-between">
        <h3 class="text-lg font-semibold text-white">Utilisation des modules</h3>
      </div>
      <div class="card-navy p-6 space-y-6">
        <div class="flex items-center justify-between border-b border-navy-800 pb-4">
          <div class="flex items-center gap-4">
            <div class="w-10 h-10 bg-blue-500/10 rounded-lg flex items-center justify-center">
              <app-doc-icon name="file-text" klass="w-5 h-5 text-blue-500"></app-doc-icon>
            </div>
            <div>
              <p class="text-sm font-semibold text-white">Documents générés</p>
              <p class="text-xs text-slate-500">Total ce mois-ci</p>
            </div>
          </div>
          <span class="text-xl font-bold text-white">1 245</span>
        </div>
        <div class="flex items-center justify-between border-b border-navy-800 pb-4">
          <div class="flex items-center gap-4">
            <div class="w-10 h-10 bg-emerald-500/10 rounded-lg flex items-center justify-center">
              <app-doc-icon name="check-circle-2" klass="w-5 h-5 text-emerald-500"></app-doc-icon>
            </div>
            <div>
              <p class="text-sm font-semibold text-white">Taux de succès API</p>
              <p class="text-xs text-slate-500">Moyenne des points de terminaison</p>
            </div>
          </div>
          <span class="text-xl font-bold text-white">99,8 %</span>
        </div>
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-4">
            <div class="w-10 h-10 bg-amber-500/10 rounded-lg flex items-center justify-center">
              <app-doc-icon name="hard-drive" klass="w-5 h-5 text-amber-500"></app-doc-icon>
            </div>
            <div>
              <p class="text-sm font-semibold text-white">Stockage utilisé</p>
              <p class="text-xs text-slate-500">Consommation blob</p>
            </div>
          </div>
          <span class="text-xl font-bold text-white">45,2 Go</span>
        </div>
      </div>
    </div>
  </div>
</div>
